### PR TITLE
Tests for proxy interface handling

### PR DESCRIPTION
**Pull request by bahusoid**
Related to #2052 and test case for #2271

Added tests to clarify expected behavior.
In 5.2 both implicit and explicit interfaces are not leading to proxy initialization on interface `Id` access.

**Update:** After #2264 implicit interfaces are **not** leading to proxy initialization on `Id` access. And explicit interfaces lead to proxy initialization. Tests are adjusted according to this behavior.

### CODE REVIEW

**Comment by hazzik** [comment]
Is this still valid?

**Comment by bahusoid** [comment]
I believe yes. It's still unclear what's expected behavior and this tests depend on decisions made for #2085. In any case I think we should have tests that cover this behavior

**Comment by bahusoid** [comment]
I've updated tests according to changes made in #2264. Also added test case for #2271

**Comment by fredericDelaporte** [comment]
So do you consider my comment [here](https://github.com/nhibernate/nhibernate-core/issues/2184#issuecomment-518018943) is not valid?

>Your case will not be fixed. You should remove the explicit implementation and only use the implicit ones. Then it should work with NHibernate 5.3, but it may depend on how we fix #2085, if we fix it.
>
>With an explicit implementation of an interface, if the entity is mapped as the concrete class, there are no way NHibernate could tell if the Id property from the interface will actually match the Id from the mapped concrete class. So instead of doing some wild guess, it must trigger the proxy loading to simply call it and see what it yields.

For me, this #2066 PR and its issue should be rejected.

**Comment by bahusoid** [comment]
> So do you consider my comment here is not valid?

I don't get it. It's not related to #2184. In #2184 - user wants to access identifier via interface without proxy initialization under different name in entity it's `EntityId` and in interface it's `Id`. So it's really no difference implicit or explicit implementation - proxy will be initialized anyway.

This PR just adds tests that shows how identifier column is handled when accessed via implicit/explicit interfaces in various scenarios. So why do you want to reject it? I see no such tests in existing codebase.

**Comment by fredericDelaporte** [comment]
I had not noticed the name was not the same. And that is not the point anyway. Two interface members having the same name and signature have no reason to be the same. That would be quite a bold assumption.

**Comment by bahusoid** [comment]
> Two interface members having the same name and signature have no reason to be the same.

Well in 5.2 both implicit/explicit identifier access doesn't trigger proxy initialization. So if name was the same - it would work in #2085. And from you comment it seems you expected proxy initialization even when name is the same.

In 5.3 you fixed explicit case. And this PR adds tests to make sure it's working  - so what's your reasons for rejecting.

**Comment by fredericDelaporte** [comment]
The reason seem to me clearly written in above quote from myself. It is now re-staten [here](https://github.com/nhibernate/nhibernate-core/pull/2264#issuecomment-553116363) too:

> I consider this behavior of explicitly implemented `Id` not leading to proxy initialization by yielding the id value very debatable, because for correctness, an `Id` which is not implemented by the declared id in mapping cannot be assumed as being the entity id. It can be something else, and unless de-compiling and analyzing the concrete class, NHibernate cannot tell.

**Comment by bahusoid** [comment]
And? Why do you think that those tests suggest otherwise? I agree with that. So why tests that make sure that proxy initialization actually occurs for explicit implementation and no proxy initialization for implicit should be rejected?

**Comment by fredericDelaporte** [comment]
Sorry, I was assuming this PR was done in the context of #2271, still considering

> It should not.

(trigger lazy load).

So why not testing this, but it is in my mind already covered [here](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate.Test/StaticProxyTest/StaticProxyFactoryFixture.cs#L435). It does test that an explicitly implemented member is not "short-circuit" to its implicitly implemented "counter-part". That is precisely what causes an explicitly implemented "id" to trigger lazy-load.

**Comment by bahusoid** [comment]
> It does test that an explicitly implemented member is not "short-circuit" to its implicitly implemented "counter-part". 

I wrote my tests a while ago - see no point dropping them now. Various scenarios for interface handling in one place. Also your tests seem to check some internal specifics of generated proxy. And my tests make no assumptions what should cause proxy initialization  - they just test actual initialization. So they more abstract from actual implementation.

Regarding #2271. Maybe it's just invalid test case and issue - will double check tomorrow.

**Comment by hazzik** [comment]
Checked locally that there is no changes in async code.

**Pull request merged**
