### PR TITLE
Upgrade AsyncGenerator to 0.19.1

### PR DESCRIPTION
**Pull request by maca88**
With this upgrade we can now generate async code also with .NET Core 3.1 and 5.0. Based on the installed .NET Core version, the appropriate async generator binaries will be used, so the `global.json` won't be needed anymore.

### CODE REVIEW

**Review by hazzik — DISMISSED** [review]

**Comment by hazzik** [comment]
I'll redo it to use a tool instead.

**Comment by hazzik** [comment]
@maca88 or you want to do it?

**Comment by maca88** [comment]
> I'll redo it to use a tool instead.

Sure, why not. Ideally would be nice to port all tools but most likely there are some that are not published as a .NET tool.

>@maca88 or you want to do it?

I am fine, you can proceed with the conversion.

**Comment by hazzik** [comment]
> Ideally would be nice to port all tools but most likely there are some that are not published as a .NET tool.

Yes, it would be great. However, only AsyncGenerator and GitReleaseManager has tool packages.

**Review by hazzik — APPROVED** [review]

**Comment by fredericDelaporte** [comment]
Has the Wip removal been overlooked, or is there still something more to do?

**Comment by maca88** [comment]
I've added WIP for upgrading from 0.19.0 to 0.19.1, which has been done. Removed it, as I think it is ready to be merged.

**Comment by hazzik** [comment]
With this change, I think, the SDK 3+ would be required.

**Review by fredericDelaporte — APPROVED** [review]
SDK 3.0 is [indeed required](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-restore), and keeping a global.json asking for a lower sdk causes the async generation to fail.

**Pull request merged**
