### PR TITLE
Update SHFB in order to build documentation without MSBuild

### PR DESCRIPTION
**Pull request by hazzik**

### CODE REVIEW

**Review by fredericDelaporte — COMMENTED** [review]
After de-installing my old SHFB and re-installing the latest one, rebooting as asked, I get this error when attempting a `nant api` in the doc folder:
```
nhibernate-core\doc> ..\Tools\nant\bin\NAnt.exe api
...
     [exec]   Building E:\Projets\nhibernate\nhibernate-core\doc\NHibernate.shfbproj
     [exec]   Initializing
     [exec] SHFB : error BE0071: Unable to locate information for the project framework version 'v4.0.30319' or a suitable redirected version on this system.  See error number help topic for details. [E:\Projets\nhibernate\nhibernate-core\doc\NHibernate.shfbproj]
```
According to [the project help](https://ewsoftware.github.io/SHFB/html/31414af7-b465-4dc3-9454-19a2d01953bc.htm), my setup would miss an adequate targeting pack.

But I have the 4.6.1 installed, which should do the job. (And also older ones: 4.5.1 and 4.5.2; and newer ones: 4.7.2, 4.8.)

Is there another thing I would miss? If yes, the "prerequisite" section of the readme needs some additional update.

**Comment by hazzik** [comment]
That is very strange

**Comment by hazzik** [comment]
I might know why. Try running `api` target in the root folder and not in doc (in doc it does not rebuild the solution) it might be that you have outdated binary. Also, maybe try `git clean`?

**Comment by fredericDelaporte** [comment]
Sorry for the delay,

I attempt right now, it fails with the same error.

```
PS E:\Projets\nhibernate\nhibernate-core> git clean
fatal: clean.requireForce defaults to true and neither -i, -n, nor -f given; refusing to clean
PS E:\Projets\nhibernate\nhibernate-core> git clean -f
PS E:\Projets\nhibernate\nhibernate-core> .\Tools\nant\bin\NAnt.exe api
...
                 [exec] SHFB : error BE0071: Unable to locate information for the project framework version 'v4.0.30319' or a suitable redirected version on this system.  See error number help topic for details.
```

The build log does not give more clues:

```
<?xml version="1.0" encoding="utf-8"?>
<shfbBuild product="Sandcastle Help File Builder and Tools" version="2022.2.6.0" projectFile="E:\Projets\nhibernate\nhibernate-core\doc\NHibernate.shfbproj" started="07/08/2022 21:31:11">
<buildStep step="Initializing">
Finding tools...
The Sandcastle tools are located in &#39;C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder&#39;
Searching for HTML Help 1 compiler...
Found HTML Help 1 compiler in &#39;C:\Program Files (x86)\HTML Help Workshop\&#39;
Locating components in the following folder(s):
    E:\Projets\nhibernate\nhibernate-core\doc
    C:\ProgramData\EWSoftware\Sandcastle Help File Builder\Components and Plug-Ins
    C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\Components
    Last step completed in 00:00:00,2665
</buildStep>
<buildStep step="Failed">

SHFB: Error BE0071: Unable to locate information for the project framework version &#39;v4.0.30319&#39; or a suitable redirected version on this system.  See error number help topic for details.
   at SandcastleBuilder.Utils.BuildEngine.BuildProcess.Build()

</buildStep>
</shfbBuild>
```

The Ci does not validate that build, since the API reference is not built by default. That is currently only a manual build done by whoever wishes to have that doc generated from NHibernate xml comments. This has been quite a long time since I have last tested it. Has anyone else tested it?

**Comment by hazzik** [comment]
Try with `git clean -fxd` (force, recursive, remove untracked)? (Careful, it would clean everything)

**Comment by bahusoid** [comment]
> But I have the 4.6.1 installed, which should do the job.

global.json?

**Comment by fredericDelaporte** [comment]
Normally global.json does not apply to the old .Net Framework, or am I wrong? Still I have tried after deleting the one in nhibernate sources since a relatively recent PR: same result.

**Comment by fredericDelaporte** [comment]
Sandcastle builder 22.2.6.0

Tried `git clean -fxd`, then `\nhibernate\nhibernate-core>Tools\nant\bin\NAnt.exe api` from old windows command line without reopening VS: it seems to work!

Once finished I will try again from within VS ps command line.

**Comment by fredericDelaporte** [comment]
It does still fail from VS powershell developper command line. No idea why. And it goes on working from windows cmd.exe.
From within VS with the "regular" developer command line, it does fail too.

I run my VS with administrative rights by default (having projects bound to the desktop IIS). Trying again while running it without administrative rights does also fail.

So the only thing I see, there seems to be some discrepancies in how the command line runs when embedded within VS versus run directly, at least for my setup. I cannot find out what, except the locale is not the same: English language under VS, French when directly run. I am not expecting this to be the culprit, especially since it would mean French locale would be required to have it work under my system, which would be very strange. I would expect the opposite, if locale is involved.

Anyway, putting aside the troubles of my setup, I approve.

**Review by fredericDelaporte — APPROVED** [review]

**Comment by hazzik** [comment]
Yep, I get the same result from Dev Command Prompt

**Comment by hazzik** [comment]
@fredericDelaporte this should fix the issue you were having.

**Review by fredericDelaporte — APPROVED** [review]
Now works both from within VS and out of it.

**Pull request merged**
