### PR TITLE
Fix session no more serializable with entities having a field interceptor

### LINKED ISSUE #1964: Unable to serialize session because SerializationFieldInfo is not marked as serializable
I can't update an application from NHibernate 5.1.4 to 5.2.2 (I've also tested 5.2.0). If I update and try to serialize an `ISession` the following exception is thrown in some cases:

```
System.Runtime.Serialization.SerializationException: Type 'System.Runtime.Serialization.SerializationFieldInfo' in Assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Runtime.Serialization.FormatterServices.<>c__DisplayClass9_0.<GetSerializableMembers>b__0(MemberHolder _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at <my code calling binaryFormatter.Serialize(memoryStream, session)>
```

Since `SerializationFieldInfo` is internal in mscorlib neither my code nor NHibernate can reference it directly. But something must have changed between NHibernate 5.1 and 5.2 that causes an `ISession` to indirectly contain a `SerializationFieldInfo` somewhere.

I'm not sure why some sessions cause this issue for me and others don't. I haven't been able to find a specific entity that causes it yet.

My application targets Framework 4.7.1 and I'm currently on the 4.7.2 runtime (Windows 10 1709).

### PR DESCRIPTION
**Pull request by hazzik**
Fixes #1964

### CODE REVIEW

**Comment by maca88** [comment]
This fix doesn't work, at least for me. I was able to [fix the issue](https://github.com/maca88/nhibernate-core/commit/6d0fec1a02ebb9ca3cb573ee2e024ac46326cbf7) by unwrapping the field info from `SerializationFieldInfo`, but I am not sure if it is the right way to do.

**Comment by hazzik** [comment]
>This fix doesn't work

Yeah, I know

**Comment by fredericDelaporte** [comment]
Maybe should the commits be squashed and a release commit be added, if intending to release 5.2.3 without waiting in case some other regressions are reported.

**Comment by hazzik** [comment]
Done

**Pull request merged**
