### PR TITLE
Batch Update with Optimistic Locking control.

### PR DESCRIPTION
**Pull request by Tikuna**
Change made to be able to use batch update when optimistic locking
control is in use.

The only diference detected is that in many case the super class StaleStateException is thrown instead of StaleObjectStateException, and in other case the StaleObjectStateException was
still in use but didn't bring any info of the EntityName and Id.

Don't know if possible to keep the original behavior regarding the excpetions. If the change have some posibilities to go further let me know and i can investigate this issue.

All test passed, but there is a change in the type of exception is
checked.

https://nhibernate.jira.com/browse/NH-3771

### CODE REVIEW

**Comment by hazzik** [comment]
Hi, @Tikuna can you check the other failing builds? The PostgreSQL and SQLite32 should not fail for sure.

**Comment by Tikuna** [comment]
Hi @hazzik 

Ups... I only checked with Sql Server.

I'm checking now the PostgreSQL and Oracle.

**Comment by Tikuna** [comment]
Hi @hazzik 

I just commit 'Test Updates' with a fix for the test OptimisticConcurrencyFixture that fix the problems for PostgreSQL and SQLite.

I didn't have the chance to see the others errores in tests, but seems that are not related with this fix.

Please let me know if this is ok, or you need anything else.

Thanks!

Best Regards

Tikuna

**Comment by Tikuna** [comment]
Hi @hazzik 

Did you have any chance to check the changes I made? 

I there anything I could help on this ?

Thanks !!!

Best regards

Tikuna

**Comment by Tikuna** [comment]
The pull request got mixed up with other changes by mistake. Will make a new pull request.

**Pull request closed without merging**
