### PR TITLE
Back port doc fixes

### PR DESCRIPTION
**Pull request by fredericDelaporte**
A bunch of fixes were done directly in html files of https://github.com/nhibernate/nhibernate.github.io, instead of being done in the documentation source files here.

I have ported back most of them. I have not ported some changes (like changing in prose `ISet` for `ISet<T>` since we can consider it implied) and adjusted slightly some others.

Some of those changes were already re-done in source here, sometime in another way: I have kept the way they were already redone. (Going generic, fixing usage of no more existent methods like `ISession.Enumerable/Find`, ...)

Most of those changes were done by @rjperes, and some by @hazzik.

### CODE REVIEW

**Comment by fredericDelaporte** [comment]
Too fast! I have made a glitch causing the doc to fail generating. Going to fix that.

**Comment by hazzik** [comment]
Ok :(

**Comment by hazzik** [comment]
+:cry:

**Comment by fredericDelaporte** [comment]
I had already forced push it, but maybe one minute after your merge...

**Pull request merged**
