### PR TITLE
Make sure dbcommand is disposed

### PR DESCRIPTION
**Pull request by RogerKratz**
DbCommands created in GenericBatchingBatcher aren't disposed.

### CODE REVIEW

**Review by fredericDelaporte — APPROVED** [review]
I have qualified it as just a minor improvement instead of a major bug because in most cases with db commands, this disposal lack will not cause an unmanaged leak and will not prevent the command from being garbage collected.

If I am wrong, this fix should then be re-tagged, but also should then target 5.3.x and likely be back-ported down to the introduction of the generic batching batcher.

**Comment by RogerKratz** [comment]
Agreed, I think it's minor as well, no unmanaged leak when `SqlCommand` is used I think. Not even sure it matters GC perf wise (maybe `GC.SuppressFinalize` is always called internally in `SqlCommand` anyhow, haven't looked closely)?

Still good to have it fixed (as "minor", yes).

**Comment by RogerKratz** [comment]
....on the other hand it might cause an unmanged leak if an other `DbCommand` than `SqlCommand` is used. However, I don't know much about these, only thinking out loud now.

**Comment by hazzik** [comment]
@fredericDelaporte maybe for 5.3.6?

**Comment by fredericDelaporte** [comment]
Why not.

**Comment by fredericDelaporte** [comment]
Changing the base did not went well, so I have made it manually with a forced push.

**Pull request merged**
