### PR TITLE
Update Travis CI to use Ubuntu Xenial on 5.3.x

### PR DESCRIPTION
**Pull request by hazzik**
Seems trusty is broken on Travis. So borrow changes from master to 5.3.x builds.

### CODE REVIEW

**Comment by hazzik** [comment]
https://www.powershellgallery.com certificate has expired :(

**Comment by bahusoid** [comment]
> https://www.powershellgallery.com certificate has expired

It's already resolved. Also if you also can't no longer restart Travis jobs you need to select Free plan in account settings.

**Review by bahusoid — APPROVED** [review]

**Comment by hazzik** [comment]
>  Also if you also can't no longer restart Travis jobs you need to select Free plan in account settings.

It seems it was needed once per org.

**Comment by bahusoid** [comment]
Ouch.. It seems setting Free plan wasn't the best idea. It looks like Travis CI is no longer free for open source projects. Not sure why builds were still running for us with no plan set (glitch in their system?) - but now with free plan we have only 1000 build minutes and then need to request OSS credits https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source

**Comment by fredericDelaporte** [comment]
Change to fix because it is obsoleted by #2812, so it will not be actually released. I will not list it in release notes.

**Pull request merged**
