### PR TITLE
Change cascade style for DefaultDirtyCheckEventListener to persist to avoid flushing the session

### LINKED ISSUE #1413: Make ISession.IsDirty() method safe, effective and useful
ISession.IsDirty() method description:
> Does this ISession contain any changes which must be synchronized with the database? Would any SQL be executed if we flushed this session?

**So expected behavior:** method should not persist any entities (work in read-only mode) and doesn't throw exceptions for dirty session.

**And current behavior:** It's very unexpected that this call can lead to exceptions or even data modifications in DB:
1) Exception is thrown when transient ManyToOne object  is present in session.
2) And data modifications - all cascaded entities are saved (which I think is very dangerous behavior)

I will try to provide failing tests today.

My use case for using this ISession.IsDirty() is the following:
```C#
var entity = LoadEntity();
//Do some modifications to entity like entity.Children.Add(child); which is mapped with Cascade.All
entity.Children.Add(CreateNewChild());

//... And at the end of the request:
if(session.IsDirty())
{
	//do some resource consuming stuff like open DTC transaction or something else that needs to be done only if database modifications are requried
	using(var dtcTransaction = OpenDTCTransaction())
	{
		session.Flush();
		//...do some stuff with legacy VB objects
	}
}

```

With current implementation I can't use `IsDirty()` as it will save child `entity.Children` elements without transaction context - very dangerous and unexpected.

If there is a valid scenario with current implementation - could you please explain it?

I understand why  cascade updates are executed - current implementation call full PreFlush life-cycle. But is it really necessary? Can't we simply check for any queued action and for any first dirty object in session?

### PR DESCRIPTION
**Pull request by hazzik**
The default cascade for it was SaveUpdate (via base AbstractFlushingEventListener) which triggered
insertion of the entities with post-insert style ID generators (eg. identity). Persist on the other hand will
make sure that insertion of the entity is delyed until flush is called.

Related to #1413

### CODE REVIEW

**Comment by hazzik** [comment]
@bahusoid @fredericDelaporte could you please review?

**Review by fredericDelaporte — APPROVED** [review]

**Comment by hazzik** [comment]
@fredericDelaporte can I please get some thoughts why this change might be a bad idea? To be honest I wasn't looking for a silent tick ;-)

**Comment by bahusoid** [comment]
Well it's not exactly immutable operation (session state is changed) but it's definitely an improvement over old behavior. So why not..

But I still would like to have IsDirty check that doesn't modify session in any way  - so maybe let's not close #1413 yet.

> why this change might be a bad idea?

Not exactly sure about real use case but something similar to https://github.com/nhibernate/nhibernate-core/issues/2632 might come up

**Comment by fredericDelaporte** [comment]
I did think a lot about what could possibly wrong by switching the cascade style for the dirty check from SaveUpdate to Persist, but I could not find anything. So I have approved.

**Comment by hazzik** [comment]
> But I still would like to have IsDirty check that doesn't modify session in any way - so maybe let's not close #1413 yet.

Sure.

**Comment by Roman-Evseev** [comment]
This change still allows IsDirty to modify the database, causing a NullReferenceException in certain scenarios. Therefore, the commit description does not accurately reflect the intended goals.

**Pull request merged**
