### PR TITLE
NH-3776 - Add Support For Fluent Configuration of Logger Factories

### PR DESCRIPTION
**Pull request by rjperes**
https://nhibernate.jira.com/browse/NH-3776

### CODE REVIEW

**Comment by hazzik** [comment]
All test fail

**Comment by rjperes** [comment]
Yes, but nothing to do with my code... right?

**Comment by hazzik** [comment]
You've forgot to initialize your new config value I believe.

**Comment by rjperes** [comment]
Yes, my fault.

**Comment by hazzik** [comment]
Still failing. Now your test.

**Comment by rjperes** [comment]
BTW, can't access http://teamcity.codebetter.com/?

**Comment by hazzik** [comment]
I can

**Comment by rjperes** [comment]
Couldn't resolve the name... but now I can too.

**Comment by rjperes** [comment]
This is trickier than I thought, because there's lots of calls to GetLogger, before Environment has the chance to actually load the value from the settings... hmmm...

**Comment by hazzik** [comment]
Maybe next time

**Pull request closed without merging**
