### PR TITLE
Remove unnecessary ID increment in SequenceHiLoGenerator

### PR DESCRIPTION
**Pull request by livioc**
fixed  using the same implementation of TableHiLoGenerator and of hibernate-java seqhilo

### CODE REVIEW

**Comment by hazzik** [comment]
Any tests?

**Comment by livioc** [comment]
i will add them but i need to execute them only with databases that support sequences, how can i do that? there are some tests with the same constraint that i can check?  thanks

**Comment by hazzik** [comment]
You can add tests only for TableHiLoGenerator itself

**Comment by livioc** [comment]
thanks, i already did the test for sqhilo.
is it better to add a specific test for nh3879 to check that the first id is the first available number in current hilo range or to add a generic test in a seqhilo specic feature as [HiLoTableGeneratorInt64Fixture](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate.Test/IdTest/HiLoTableGeneratorInt64Fixture.cs) to check that we will use all the available ids in the range?

**Comment by hazzik** [comment]
Can you please enable [Allow edits from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) option on this PR?

**Comment by livioc** [comment]
Allowed

**Pull request merged**
