### PR TITLE
Projection performance improvements [NH-3486]

### PR DESCRIPTION
**Pull request by JesperD60**
https://nhibernate.jira.com/browse/NH-3486

I have implemented the changes suggested by reporter.

### CODE REVIEW

**Comment by hazzik** [comment]
@JesperD60 preferable way is to cache these properties at CriteriaLoader

**Comment by lnu** [comment]
You mean like this?
https://github.com/lnu/nhibernate-core/commit/626f8d43a61b2ab5b4c53e8b7ca6328a90338abf

**Comment by hazzik** [comment]
@lnu does it work? If so, please make a PR

**Comment by lnu** [comment]
All the tests are ok.

**Comment by hazzik** [comment]
Closed in favor of #468

**Pull request closed without merging**
