### PR TITLE
NH3820 | Support for Join QueryHints like merge, hash, loop and Nolock

### PR DESCRIPTION
**Pull request by osoykan**
https://nhibernate.jira.com/browse/NH-3820

### CODE REVIEW

**Comment by hazzik** [comment]
@osoykan other databases are failing tests on these changes. You need to either restrict tests to MS SQL only, or implement query hints for other RDBMS

**Comment by osoykan** [comment]
@hazzik Exactly some of databases not support hints, im on it.

**Comment by osoykan** [comment]
@hazzik Have you had any chance to review it, could be part of 4.1.0 ?

**Comment by hazzik** [comment]
@osoykan, sorry. Not yet

**Pull request closed without merging**
