### PR TITLE
Release 5.3.7

### PR DESCRIPTION
**Pull request by fredericDelaporte**
Release 5.3.7.

### CODE REVIEW

**Review by hazzik — APPROVED** [review]

**Comment by fredericDelaporte** [comment]
Rebased and updated.
I intend to publish it tomorrow.

**Comment by bahusoid** [comment]
You didn't merge changes to master... Is it intentional or just omission?

**Comment by fredericDelaporte** [comment]
I forgot it. I will do it tomorrow if not already done by someone else.

**Comment by fredericDelaporte** [comment]
Done.

**Pull request merged**
