### PR TITLE
NH-3877 Target Net 4.6.2 and upgrade solution files to VS2015

### PR DESCRIPTION
**Pull request by oskarb**

### CODE REVIEW

**Comment by oskarb** [comment]
I take it you mean ilrepack?

**Comment by hazzik** [comment]
Yes, that one

**Comment by oskarb** [comment]
I added a little something for ilrepack - not really sure if it's correct or the best way to do it.

**Comment by hazzik** [comment]
Looks legit

**Comment by igitur** [comment]
Hope it's OK if I add on to this issue. I see this is the issue that removed `net40` support. For me, that's OK, but is supporting for `net452` not possible with multi-targeting in VS2017?

**Comment by fredericDelaporte** [comment]
The code uses some classes not available in `net452`, like `AsyncLocal<T>`.

**Pull request merged**
