### PR TITLE
NH-3470 - Allow Session.Query to load entities as read-only

### PR DESCRIPTION
**Pull request by rjperes**
https://nhibernate.jira.com/browse/NH-3470

### CODE REVIEW

**Comment by Sebazzz** [comment]
@hazzik Extension methods are consistent with how the LINQ API is designed though, and are consistent with how NHibernate currently works (`Cacheable` for example). It is also consistent with other ORM.

**Comment by rjperes** [comment]
Also, why is the PR broken?

**Comment by rjperes** [comment]
@hazzik hello?

**Comment by hazzik** [comment]
> @hazzik Extension methods are consistent with how the LINQ API is designed though
I don't like this pollution with extension methods. And it makes harder to analyze expression tree.

>@hazzik hello?

Moving house and don't have internet connection at home.

**Comment by hazzik** [comment]
>Also, your proposal doesn't allow flexible setting the query options later on in the query, for example what Cacheable allows (or the criteria API for example).

This is a fair point, but the way this is implemented is wrong, it should just call a method on INhQueryable to set required option, but not produce additional node types, result operators and unnecessary complications to the expression tree.

**Comment by hazzik** [comment]
>Also, why is the PR broken?

I don't know why

**Comment by hazzik** [comment]
Replaced by #418

**Pull request closed without merging**
