### PR TITLE
The proposed fix for NH-3757 "Dynamic entity mapped with entity-name cannot have a component of a fixed class"

### PR DESCRIPTION
**Pull request by ogvolkov**
A fix for "Dynamic entity mapped with entity-name cannot have a component of a fixed class"
https://nhibernate.jira.com/browse/NH-3757

### CODE REVIEW

**Comment by ogvolkov** [comment]
What's wrong with this PR? It's pretty trivial but it's been in limbo for the past six+ months...What can I do to make things going?

**Comment by ogvolkov** [comment]
Hello, can we proceed with this patch, as it's been in limbo for two years? Granted it's not critical at all, but the changes are pretty minor, so what can I do to make sure it's merged?

**Comment by fredericDelaporte** [comment]
In case some one try to check what going on with this feature on Hibernate side, here is my findings.

On Hibernate side, the feature of mixing dynamic with fixed seems to have been dropped with [HHH-6330](https://hibernate.atlassian.net/browse/HHH-6330), without much explanations in their tracking tool. At least, its commit delete the [equivalent file](https://github.com/hibernate/hibernate-orm/commit/4a4f636caf9ecc62fe0d230f422ad3eab2517db0#diff-87) to the one you have modified in NHibernate.  
This file was still holding the condition you want to remove. And in their GitHub repository, this file first version was already having this condition.

So I guess the rational behind this condition being there in the first place is lost. (Unless someone knows where to look for previous to GitHub history of that file in Hibernate.)

**Comment by hazzik** [comment]
It has been moved here:

https://github.com/hibernate/hibernate-orm/commit/4a4f636caf9ecc62fe0d230f422ad3eab2517db0#diff-ec0cf8552c814a18b82690c9d5cb4136R76

**Comment by hazzik** [comment]
This logic follows hibernate logic from what I can see.

**Comment by hazzik** [comment]
@ogvolkov could you please squash and rebase on top of master, or enable the "Allow changes by maintainers" feature?

**Comment by hazzik** [comment]
Ok, merged. No action is required. Thanks.

**Pull request merged**
