### PR TITLE
NH-3953 - Added take clause to ProcessSingle, similar to ProcessFirst

### PR DESCRIPTION
**Pull request by nkreipke**
Probably optimizes the records returned by the database.

### CODE REVIEW

**Comment by fredericDelaporte** [comment]
Well, adding `top 2` may optimize a failure case for `Single`: more than one element, and for this to optimize, even more than two.
The normal, not failing case will not be optimized by this change: only one element, or none in case of `OrDefault`.
Still an optimization, but for an edge case I think, contrary to the almost same code for `First`.

Anyway, I think you should probably add an improvement issue in [NHibernate Jira](https://nhibernate.jira.com) too for a better change tracking. (I am not from NHibernate team though, this is just my opinion.)

**Comment by hazzik** [comment]
Hi @nkreipke. Please add a JIRA issue.

**Comment by nkreipke** [comment]
Added a [JIRA issue NH-3953](https://nhibernate.jira.com/browse/NH-3953).

**Comment by fredericDelaporte** [comment]
I now think this may be a breaking change for fetching cases with `Single`. In case a `FetchMany` is done, it will, with this PR, only be able of loading the two first related entities at most.

Yes, `FetchMany` is already broken with `First`, but is it a reason for having it broken with `Single` too?

As said in a previous comment, this change is only optimizing some failure cases anyway. And now it looks to me it creates a bug for passing cases.

(While the `take 1` for `First` optimize passing cases too, and removing it for supporting `FetchMany` may cause passing cases to have unacceptable performances.)

Maybe I am wrong: I have not written test cases for checking that `FetchMany` currently works as intended with three or more children to load and `Single`, and do no more works with this PR. Such a test case should probably be added to this PR.

**Comment by hazzik** [comment]
good points @fredericDelaporte 

Actually, I think, that we need to disallow (eg throw an exception) users to combine eager fetching with paging (there are several JIRAs have been closed as "Not an issue" for criteria api, and some still open for Linq).

**Comment by fredericDelaporte** [comment]
Disallowing `FetchMany` with `Skip` or `Take` will make sens. But `Fetch` should probably remain allowed, when not used on collections (it appears it works on collection too, apart it does not allow proper use of `ThenFetch` or `ThenFetchMany` if `Fetch` is used on a collection).

Supporting `FetchMany` with `Skip` or `Take` does not look impossible to me, but this would require supporting sub-queries in `from` statement. Probably not an easy task.

**Pull request closed without merging**
