### PR TITLE
Add .net 6 and net48 targets

### PR DESCRIPTION
**Pull request by bahusoid**

### CODE REVIEW

**Comment by bahusoid** [comment]
Looks like ANTLR generator has some concurrency issue as github build now throw from time to time exceptions like:
```C#
Error: /home/runner/.nuget/packages/antlr3.codegenerator/3.5.2-rc1/build/Antlr3.CodeGenerator.targets(146,5): error AC1000: Unknown build error:  : error 10 : internal error:  : System.IO.FileNotFoundException: Could not find file '/home/runner/work/nhibernate-core/nhibernate-core/src/NHibernate/obj/Release/netcoreapp2.0/Hql__.g'. File name: '/home/runner/work/nhibernate-core/nhibernate-core/src/NHibernate/obj/Release/netcoreapp2.0/Hql__.g'    
at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)    
at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)    
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)    
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)    
at Antlr3.Tool.GrammarSpelunker.Parse()   
...
```

**Comment by hazzik** [comment]
Why do we need net48 target in the library? In test I understand, and wanted to implement it, but in the library?

**Comment by bahusoid** [comment]
> Why do we need net48?

Why not? Since it's already used in tests, I thought it wouldn't hurt to have it for lib too. And some optimizations are still possible on this target (like  [here](https://github.com/nhibernate/nhibernate-core/blob/ecfa47893a515084bd0b100f9afe8a612f3d5fb0/src/NHibernate/Collection/Generic/SetHelpers/SetSnapShot.cs#L12-L13))

**Comment by bahusoid** [comment]
@fredericDelaporte Seems **hazzik** made it up to you (enabled auto-merge). Any objections?

**Comment by hazzik** [comment]
I wanted to merge it after some other PR and after 5.3.x merge. Also, I’m a little hesitant on adding .NET4.8 target.

**Comment by fredericDelaporte** [comment]
I think it makes sense to add that 4.8 target, provided we consider the NuGet size is not an issue. .Net Framework is far from its end of life: enabling some more optimizations already done for other targets should be beneficial to lots of users.

(I have seen a 4.8.1 has been released in August, but we should not target it in my opinion. It adds arm support, which users can still get by targeting their application on 4.8.1, without needing NHibernate targeting it too. Moreover that version is available only on most recent versions of Windows OSes.)

**Comment by fredericDelaporte** [comment]
I mean the former, like mentioned by Roman.

> Why not? Since it's already used in tests, I thought it wouldn't hurt to have it for lib too. And some optimizations are still possible on this target (like  [here](https://github.com/nhibernate/nhibernate-core/blob/ecfa47893a515084bd0b100f9afe8a612f3d5fb0/src/NHibernate/Collection/Generic/SetHelpers/SetSnapShot.cs#L12-L13))

**Comment by hazzik** [comment]
@fredericDelaporte please approve and merge if you're happy with the changes

**Review by fredericDelaporte — APPROVED** [review]

**Pull request merged**
