### PR TITLE
NH-2888 - Add support to ICriteria to eager fetch lazy properties

### LINKED ISSUE #972: NH-2888 - Add 'fetch all properties' support to ICriteria
**Stuart Carnie** created an issue — <time datetime="2011-09-15T23:54:34.132Z" title="2011-09-15T23:54:34.132Z">15th September 2011, 23:54:34</time>:
> Only hql style queries support eager fetching of lazy-loaded properties.  Request support for this via ICriteria.FetchAllProperties()
> 
---
**Stuart Carnie** added a comment — <time datetime="2011-09-20T21:25:21.804Z" title="2011-09-20T21:25:21.804Z">20th September 2011, 21:25:21</time>:
> Added the following pull request: https://github.com/nhibernate/nhibernate-core/pull/11
> 
---
**Oskar Berggren** added a comment — <time datetime="2012-01-29T21:52:37.391Z" title="2012-01-29T21:52:37.391Z">29th January 2012, 21:52:37</time>:
> Mailing list discussion from sep 2011:
> https://groups.google.com/d/topic/nhibernate-development/I0s-HJX9E1Y/discussion
> 
---
**Hamdanil Rasyid** added a comment — <time datetime="2013-01-22T11:01:17.660Z" title="2013-01-22T11:01:17.660Z">22nd January 2013, 11:01:17</time>:
> any update?
> 
---
**Dawid Ciecierski** added a comment — <time datetime="2014-05-17T09:41:29.186Z" title="2014-05-17T09:41:29.186Z">17th May 2014, 9:41:29</time>:
> Does `SetFetchMode(association, FetchMode)` not do something similar? If you need it for all properties, then perhaps a custom extension method would be a better way forward, as other providers do not have this functionality either AFAIK.
> 
---
**Maximilian Haru Raditya** added a comment — <time datetime="2014-09-28T10:46:13.182Z" title="2014-09-28T10:46:13.182Z">28th September 2014, 10:46:13</time>:
> Does HQL support fetching any lazy property individually, instead of fetching the whole lazy properties?
> 
---
**Ricardo Peres** added a comment — <time datetime="2014-09-28T12:31:40.902Z" title="2014-09-28T12:31:40.902Z">28th September 2014, 12:31:40</time>:
> <~mahara>: only joined collections:
> 
> 
> ```
> 
> from Product p join fetch p.Orders
> 
> ```
> 
>

### PR DESCRIPTION
**Pull request by hazzik**
Opened instead of #11, fix #972.
- [ ] Extend QueryOver API

### CODE REVIEW

**Comment by hazzik** [comment]
Why?

**Comment by oskarb** [comment]
Well, the automatic and unannounced (to me) closing of all these PRs was certainly not expected. :)  Guess it makes sense for the system to act that way though.

**Comment by hazzik** [comment]
Yep, I understood that.

**Comment by fredericDelaporte** [comment]
Replaced by #1599

**Pull request closed without merging**
