### PR TITLE
Avoid double param type guessing and better NULL parameter handling in LINQ

### PR DESCRIPTION
**Pull request by bahusoid**
And added test cases for #1166

### CODE REVIEW

**Comment by hazzik** [comment]
> Figure out why firebird generates ...

Because Firebird requires parameters to be casted.

**Comment by hazzik** [comment]
@bahusoid please resolve conflicts.

Also as I understand some changes needs to be reverted from 5.3.9

**Comment by bahusoid** [comment]
I believe it would also need changes similair to https://github.com/nhibernate/nhibernate-core/pull/2836

**Comment by bahusoid** [comment]
> please resolve conflicts.
Also as I understand some changes needs to be reverted from 5.3.9

Done

**Comment by fredericDelaporte** [comment]
There is a conflict with #2964 to resolve.

**Comment by hazzik** [comment]
Hopefully I've resolved the conflict correctly. @maca88 and @bahusoid could you please check.

**Comment by maca88** [comment]
From my point of view the conflict was correctly solved. Even if the modification in `GetCharsGenerator` class fixes the tests, I would still leave the change from #2964 as there could be other cases (e.g. with user defined hql functions) for which we don't have tests.

**Comment by bahusoid** [comment]
It seems some of the changes no longer needed. I need to look at it more closely when I have time...

**Comment by bahusoid** [comment]
#2964 implements most of the logic of original PR. Now this PR is transformed in parameter handling improvement so changed the name.

**Review by fredericDelaporte — APPROVED** [review]

**Review by hazzik — APPROVED** [review]

**Pull request merged**
