### PR TITLE
fixed a ton of xmldoc typo errors

### PR DESCRIPTION
**Pull request by sean-gilliam**
wasn't sure how to break this up but all the typo fixes look to be
simple typing mistakes.

### CODE REVIEW

**Comment by hazzik** [comment]
@sean-gilliam what did you use to find all these errors?

**Comment by sean-gilliam** [comment]
@hazzik [ReSpeller](https://resharper-plugins.jetbrains.com/packages/EtherealCode.ReSpeller/)

**Comment by hazzik** [comment]
@sean-gilliam can you please rebase on master? I fixed the build and this should work now.

**Comment by sean-gilliam** [comment]
@hazzik okay hopefully i did that right.

**Comment by hazzik** [comment]
Yep, all good

**Pull request merged**
