### PR TITLE
[WIP] NH-3807 Support for .NET Core 1.0

### PR DESCRIPTION
**Pull request by ngbrown**
[Link to the NH-3807 issue in Jira](https://nhibernate.jira.com/browse/NH-3807)

This is currently a work in progress.  It does compile and I have ran simple programs against it.

A majority of the changes were done to the mainline .NET version so all the mainline tests could be used during development.  There are no tests ported to .NET Core yet, and this may be difficult without the dynamic schema support.

By necessity, it includes ~[#241](https://github.com/nhibernate/nhibernate-core/pull/241)/[NH-3431 - Replace System.Data with System.Data.Common](https://nhibernate.jira.com/browse/NH-3431) and~ [NH-3853 - Switch binary-serialization to an implementation that is supported by CoreClr](https://nhibernate.jira.com/browse/NH-3853).

There are a number of compromises that have to take place on .NET Core, chief among them is that there is no `GetSchemaTable()`.  Without this, none of the dynamic schema generation or updates works.  The tests, when implemented, will need a static schema checked into the repository for database restoration.

I think that NHibernate has a number of great features above what Entity Framework is providing and this prevents the choice of .NET Core as being the deciding factor against NHibernate.

Please try this branch out and work to help make it a reality.
### Conditional Compilation Symbols

[(source for table)](https://gist.github.com/ngbrown/30701c11ec58d784d3deb4c95296b1f8#file-wip-nh-3807-pull-request-md)

The following conditional compilation symbols (vertical) are currently defined for each of the build configurations (horizontal):

| Symbol | NET40 | NET45 | .NET Core |
| --- | --- | --- | --- |
| `FEATURE_ADONET_SQLCOMMANDSET` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_APPDOMAIN` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_ASSEMBLYBUILDER_SAVE` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_BINDINGLIST` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_CODEDOM` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_DATA_CLOSE` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_DATA_GETCOLUMNSCHEMA` | :no_entry_sign: | :no_entry_sign: | :white_check_mark: |
| `FEATURE_DATA_GETSCHEMATABLE` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_DBPROVIDERFACTORIES` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_INTERNALIZE_IESI` | :no_entry_sign: | :no_entry_sign: | :white_check_mark: |
| `FEATURE_NETCORE_ICLONEABLE_API` | :no_entry_sign: | :no_entry_sign: | :white_check_mark: |
| `FEATURE_NETCORE_REFLECTION_API` | :no_entry_sign: | :no_entry_sign: | :white_check_mark: |
| `FEATURE_ODBC_OLEDB` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_REFLECTEDTYPE` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_REMOTING` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_SECURITY_PERMISSIONS` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_SERIALIZATION` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_STRING_INTERN` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_SYSTEM_CONFIGURATION` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_SYSTEM_SERVICEMODEL` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_SYSTEM_TRANSACTIONS` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_WEB_SESSION_CONTEXT` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_XML_SCHEMAS` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `FEATURE_XML_VALIDATIONEVENTHANDLER` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| --- |  |  |  |
| `NET_4_0` | :white_check_mark: | :white_check_mark: | :no_entry_sign: |
| `NETSTANDARD` | :no_entry_sign: | :no_entry_sign: | :white_check_mark: |
- `FEATURE_ADONET_SQLCOMMANDSET` - enables support for accessing the internal SqlCommandSet for batching.  Otherwise, no batching is enabled.
- `FEATURE_APPDOMAIN` - enables support for features that make use of an AppDomain in the host.
- `FEATURE_ASSEMBLYBUILDER_SAVE` - enabled support for saving the dynamically generated proxy assembly.
- `FEATURE_BINDINGLIST` - enables support features that make use of System.ComponentModel.BindingList.
- `FEATURE_CODEDOM` - enables support for CodeDom providers such as CSharpCodeProvider.
- `FEATURE_DATA_CLOSE` - enables support for DbDataReader.Close().  .NET Core doesn't have this
- `FEATURE_DATA_GETCOLUMNSCHEMA` - .NET Core has IDbColumnSchemaGenerator.GetDbColumnSchema on the DbDataReader implementations.
- `FEATURE_DATA_GETSCHEMATABLE` - DbConnection has GetSchema implementation and DbDataReader has GetSchemaTable. .NET Core has IDbColumnSchemaGenerator.GetDbColumnSchema on the DbDataReader implementations.
- `FEATURE_DBPROVIDERFACTORIES` - Has DbProviderFactories with globally registered DB providers.  Otherwise needs driver assembly with specific name.
- `FEATURE_INTERNALIZE_IESI` - Since NHibernate 4.0, only LinkedHashSet has been used from Iesi.Collections.  We can internalize this and not refer to an external assembly.
- `FEATURE_LEGACY_REFLECTION_API` - provides a shim for .NET 4.0 that emulates the `TypeInfo` API available in .NET 4.5+ and .NET Core.
- `FEATURE_NETCORE_ICLONEABLE_API` - provides shims for missing ICloneable interface
- `FEATURE_NETCORE_REFLECTION_API` - provides shims to implement missing functionality in .NET Core that has no alternatives.
- `FEATURE_ODBC_OLEDB` - enables support for features that make use of System.Data.Odbc or System.Data.OleDb.
- `FEATURE_REFLECTEDTYPE` - Get more precise information from what type a MemberInfo was retreived.  Used in MapByCode, but not available in .NET Core.
- `FEATURE_REMOTING` - supports remoting on various types including inheriting from MarshalByRefObject.  Both System.Runtime.Remoting and WCF System.ServiceModel.
- `FEATURE_SECURITY_PERMISSIONS` - enables the use of CAS and Security[Critical|SafeCritical|Transparent].
- `FEATURE_SERIALIZATION` - enables support for serialization of dynamic proxies and other types.
- `FEATURE_STRING_INTERN` - enables support for string.Intern()
- `FEATURE_SYSTEM_CONFIGURATION` - enables features that use System.Configuration and the ConfigurationManager.
- `FEATURE_SYSTEM_SERVICEMODEL` enables features that use System.ServiceModel such as WCF and OperationContext.
- `FEATURE_SYSTEM_TRANSACTIONS` - enables features that use System.Transactions.
- `FEATURE_WEB_SESSION_CONTEXT` - enables WebSessionContext and relies on System.Web.HttpContext.
- `FEATURE_XML_SCHEMAS` - enables features around XmlSchema including XmlSchemaSet
- `FEATURE_XML_VALIDATIONEVENTHANDLER` - enables handling ValidationEventHandler events.

### CODE REVIEW

**Comment by danielcweber** [comment]
Great work. Would it make sense to factor NHibernate's functionality into smaller components (assemblies) so that some components may run on ntetstandard while others would only run on a full framework?

**Comment by ngbrown** [comment]
The most obvious part that could be sliced off is the `NHibernate.Tool.hbm2ddl` namespace and the associated `NHibernate.Dialect.Schema` namespaces.  These areas currently do not work as written with .Net Core and it's questionable if they ever will.  See dotnet/corefx#3423 and dotnet/corefx#5024.

Most likely an alternative approach will have to be made where the NHibernate hbm2ddl functionality, that is schema synchronization, knows how to talk to the database meta-tables instead of relying on the driver to do it.  This may be easier if it is already refactored into a separate library.

For example, Entity Framework Core talks to each kind of database through SQL commands to get the database metadata:  [/Microsoft.EntityFrameworkCore.Sqlite.Design/Internal/SqliteDatabaseModelFactory.cs](https://github.com/aspnet/EntityFramework/blob/7c17eb7e53863c3087de4269db019777e476e31b/src/Microsoft.EntityFrameworkCore.Sqlite.Design/Internal/SqliteDatabaseModelFactory.cs).

Another part that is a possibility, is how the various database drivers are demand loaded through reflection.  I don't know if they will all be consistent over to the .Net Core world and it might make sense to have each type of database support refactored out into separate libraries.  The database support libraries could then link for real with their respective drivers and pull them down from NuGet as dependencies.

I hope you can join in and see what can be done.

**Comment by mattzink** [comment]
> These areas currently do not work as written with .Net Core and it's questionable if they ever will. See dotnet/corefx#3423 and dotnet/corefx#5024.

Microsoft has recently [stated ](https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/) that they are adding back the full data API of .NET Framework for .NET Standard 2.0, so these scenarios will certainly be supported again in the first half of 2017.

**Comment by ngbrown** [comment]
@mattzink Yes, they seem to be adding serialization back in, but that is the least of NHibernates problems.  There has been no commitment to bringing `DbConnection.GetSchema()` and `DataTable` back. See dotnet/corefx#5024 and dotnet/corefx#1039.

I think the path forward is to get at least some of the tests running without requiring dynamic schema generation, and then start working on pulling each database schema in implementation specific ways instead of relying on ADO.Net.

Any thoughts on this?  Would any database's schema and hbm2ddl methods benefit by being more database specific rather than relying on ADO.Net providers?

**Comment by jeffreyabecker** [comment]
Right now it looks like many of the dialects rely on AbstractDatabaseSchema to do most of the work of getting the schema.  Would it be possible to have that class expose utility methods for querying INFORMATION_SCHEMA?

**Comment by ngbrown** [comment]
Microsoft has announced their direction on [.NET Standard 2.0](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/).  Basically, they are adding back `BinaryFormatter` for serialization, but appear to be totally removing `System.Data`.  NHibernate worked with serialization, but didn't really depend on it for any major functionality.  It does however heavily depend on `System.Data`.

Entity Framework has pulled everything it needs out of `System.Data` and put it into `Microsoft.Data`.  See aspnet/EntityFramework#2665.

What is NHibernate's position for the future going to be?  I've heard from companies I work with that they liked NHibernate in the past, but are moving to Entity Framework because it runs on .NET Core.  How is NHibernate going to stay relevant?

**Comment by gliljas** [comment]
By doing the same, I would say.

/G

2016-09-29 16:08 GMT+02:00 Nathan Brown <notifications@github.com>:

**Comment by hazzik** [comment]
can we resue Microsoft.Data?

**Comment by ngbrown** [comment]
@hazzik It's not so much as there is a library to re-use, but that Entity Framework itself implements whatever it needs to that was missing.

**Comment by hazzik** [comment]
Do I understand correctly that with .NETStandard 2.0 only the minimal work will be required?

**Comment by milla** [comment]
FEATURE_XML_SCHEMAS this change impacts schema validation which is one of our key features, is there already a plan on the release data for this with .net core?

**Comment by ssinno28** [comment]
I'm having an issue with Antlr3.Runtime being compatible with .Net Standard 1.6.. how do you get it compile? Did you just include "dnx451"? I want to get it to work cross platform, do we need to upgrade to antlr4.runtime (which seems to be compatible with aspnet core)?

**Comment by ngbrown** [comment]
@ssinno28 I used `Antlr3.Runtime`.  I made my own build and the NuGet package feed is available at `https://ci.appveyor.com/nuget/antlrcs-xwvu6kkh1nnu`.  I used version  `3.5.0.3-dev-201608090747`.

It's from my own branch https://github.com/ngbrown/antlrcs/tree/fix-version which is mostly just fixes to the `appveyor.yml` file.

**Comment by darklx** [comment]
Any follow-up?

**Comment by darklx** [comment]
Any follow-up?

**Comment by ssinno28** [comment]
Adding the nuget package URL worked.. Since VS 2017 RC came out I've been having issues with the new way they are using the .csproj... For whatever reason it is refusing to build.. going to wait until the nhibernate team decides to convert it to .Net core which is when .Net standard 2.0 is getting released..

**Comment by hazzik** [comment]
@ngbrown I'm going to rebase your changes on top of master (it means drop some of the commits) and migrate to VS2017 format.

**Comment by hazzik** [comment]
Rebased on top of master & converted to VS2017 (.NET SDK 1.0.1)

**Comment by hazzik** [comment]
Closing this for now. Thanks for the great work, @ngbrown.

**Comment by darklx** [comment]
@hazzik @ngbrown 
It means NHibernate now supports .NET Core ?

**Comment by hazzik** [comment]
@darklx no. 

This PR was targeting .NET Core 1.0. NHibernate is going to support .NET Core 2.0 and the work required is hardly intersected with this PR.

**Comment by darklx** [comment]
@hazzik 
Okay,Thanks for the great work !
Should we use this .NET Core 1.0 version NHibernate on production ?

**Comment by hazzik** [comment]
I don't think that you can even compile this version:) So, - no.

**Comment by darklx** [comment]
@hazzik 
Hah Hah Hah, OK, I Know~

**Pull request closed without merging**
