### PR TITLE
Call BeforeAssemble on persistent collections' InitializeFromCache to allow batched cache fetching

### LINKED ISSUE #3359: AbstractPersistentCollection InitializeCollectionFromCache performance
I believe there is an issue in second level cache when NHibernate initializing a collection which call GetMany to get all values for array of keys but then when it goes into for loop to Assemble then it again calls GetMany for each item

I have Entity which has a bag collection of EntityFields and both have `batch-size=2000` attribute. When I try to load the collection EntityFields then NHibernate calls `DefaultInitializeCollectionEventListener.InitializeCollectionFromCache` then it gets a 2000 CacheKey which calls `GetMany()` till that point everything is fine but then it goes inside `CacheEntry.Assemble` which calls `InternalLoad` and `DoLoad` which again tries to load from the cache `LoadFromSecondLevelCache` and calls again GetMany ... attached the call stack image.

My understanding is that once it found it all in Second Level Cache then it should not keep calling `GetMany` again for each record one by one, right?

Stack

### PR DESCRIPTION
**Pull request by hazzik**
Fixes #3359

### CODE REVIEW

**Comment by bahusoid** [comment]
I probably OK with this fix though I don't think it's fully correct.
Currently it calls `ScheduleBatchLoadIfNeeded(object id, ISessionImplementor session, bool addToQueryCacheBatch)`
with `addToQueryCacheBatch` set to true. But it this context query cache seems irrelevant so it should be `false`

**Comment by hazzik** [comment]
I think it does not really matter. In this case the `QueryCacheQueue` will likely be `null` and so the parameter would be, pretty much, ignored.

**Review by fredericDelaporte — APPROVED** [review]

**Comment by fredericDelaporte** [comment]
Though, why 5.4? It does not look like a regression.

**Comment by hazzik** [comment]
> why 5.4? It does not look like a regression.

Yes, it is not regression, but a really nasty bug that renders collection cache unusable in some cases.

**Comment by fredericDelaporte** [comment]
Ok.

**Pull request merged**
