### PR TITLE
Fix Get failing with a null exception

### LINKED ISSUE #1920: ISession.Get may fail with a null exception
`ISession.Get` fails with an "`InvalidOperationException` : Nullable object must have a value" when the entity class has batch lazy-loads enabled and at least one but less than `batch-size` other instances of the entity class are proxies awaiting loading.
(The get has to be done on an entity not yet loaded, even as an uninitialized proxy.)

Initial report:
---

Regression bug for 5.2.

We have a bunch of tests that after upgrade to 5.2 fails with stack trace below. Tried to figure out what/when this occur but no success yet. I guess there are some particular mapping that causes this? 
It happens both in tests when Get as well as Merge is called. 

The commit when this was added was 09120c02b3816f92d154e4c5b0e47daa0171eb16. 

I've tried to isolate this problem to a small test but haven't really found out what causes this. ping @maca88 - do you have a guess when this could happen?

```
System.InvalidOperationException : Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at NHibernate.Engine.BatchFetchQueue.<GetEntityBatch>g__CheckCacheAndProcessResult|25_0(<>c__DisplayClass25_0& )
   at NHibernate.Engine.BatchFetchQueue.GetEntityBatch(IEntityPersister persister, Object id, Int32 batchSize, Boolean checkCache)
   at NHibernate.Loader.Entity.BatchingEntityLoader.Load(Object id, Object optionalObject, ISessionImplementor session)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Load(Object id, Object optionalObject, LockMode lockMode, ISessionImplementor session)
   at NHibernate.Event.Default.DefaultLoadEventListener.LoadFromDatasource(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.DoLoad(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.Load(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.ProxyOrLoad(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.OnLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.FireLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.InternalLoad(String entityName, Object id, Boolean eager, Boolean isNullable)
   at NHibernate.Type.EntityType.ResolveIdentifier(Object id, ISessionImplementor session)
   at NHibernate.Type.EntityType.Replace(Object original, Object target, ISessionImplementor session, Object owner, IDictionary copyCache)
   at NHibernate.Type.CollectionType.ReplaceElements(Object original, Object target, Object owner, IDictionary copyCache, ISessionImplementor session)
   at NHibernate.Type.CollectionType.Replace(Object original, Object target, ISessionImplementor session, Object owner, IDictionary copyCache)
   at NHibernate.Type.TypeHelper.Replace(Object[] original, Object[] target, IType[] types, ISessionImplementor session, Object owner, IDictionary copiedAlready)
   at NHibernate.Event.Default.DefaultMergeEventListener.CopyValues(IEntityPersister persister, Object entity, Object target, ISessionImplementor source, IDictionary copyCache)
   at NHibernate.Event.Default.DefaultMergeEventListener.EntityIsDetached(MergeEvent event, IDictionary copyCache)
   at NHibernate.Event.Default.DefaultMergeEventListener.OnMerge(MergeEvent event, IDictionary copiedAlready)
   at NHibernate.Impl.SessionImpl.FireMerge(IDictionary copiedAlready, MergeEvent event)
   at NHibernate.Impl.SessionImpl.Merge(String entityName, Object obj, IDictionary copiedAlready)
   at NHibernate.Engine.CascadingAction.MergeCascadingAction.Cascade(IEventSource session, Object child, String entityName, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeToOne(Object parent, Object child, IType type, CascadeStyle style, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeCollectionElements(Object parent, Object child, CollectionType collectionType, CascadeStyle style, IType elemType, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeCollection(Object parent, Object child, CascadeStyle style, Object anything, CollectionType type)
   at NHibernate.Engine.Cascade.CascadeAssociation(Object parent, Object child, IType type, CascadeStyle style, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeOn(IEntityPersister persister, Object parent, Object anything)
   at NHibernate.Event.Default.DefaultMergeEventListener.CascadeOnMerge(IEventSource source, IEntityPersister persister, Object entity, IDictionary copyCache)
   at NHibernate.Event.Default.DefaultMergeEventListener.EntityIsDetached(MergeEvent event, IDictionary copyCache)
   at NHibernate.Event.Default.DefaultMergeEventListener.OnMerge(MergeEvent event, IDictionary copiedAlready)
   at NHibernate.Impl.SessionImpl.FireMerge(IDictionary copiedAlready, MergeEvent event)
   at NHibernate.Impl.SessionImpl.Merge(String entityName, Object obj, IDictionary copiedAlready)
   at NHibernate.Engine.CascadingAction.MergeCascadingAction.Cascade(IEventSource session, Object child, String entityName, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeToOne(Object parent, Object child, IType type, CascadeStyle style, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeCollectionElements(Object parent, Object child, CollectionType collectionType, CascadeStyle style, IType elemType, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeCollection(Object parent, Object child, CascadeStyle style, Object anything, CollectionType type)
   at NHibernate.Engine.Cascade.CascadeAssociation(Object parent, Object child, IType type, CascadeStyle style, Object anything, Boolean isCascadeDeleteEnabled)
   at NHibernate.Engine.Cascade.CascadeOn(IEntityPersister persister, Object parent, Object anything)
   at NHibernate.Event.Default.DefaultMergeEventListener.CascadeOnMerge(IEventSource source, IEntityPersister persister, Object entity, IDictionary copyCache)
   at NHibernate.Event.Default.DefaultMergeEventListener.EntityIsDetached(MergeEvent event, IDictionary copyCache)
   at NHibernate.Event.Default.DefaultMergeEventListener.OnMerge(MergeEvent event, IDictionary copiedAlready)
   at NHibernate.Event.Default.DefaultMergeEventListener.OnMerge(MergeEvent event)
   at NHibernate.Impl.SessionImpl.FireMerge(MergeEvent event)
   at NHibernate.Impl.SessionImpl.Merge(String entityName, Object obj)
   at NHibernate.Impl.SessionImpl.Merge[T](T entity)
```

### PR DESCRIPTION
**Pull request by RogerKratz**
Fixes #1920

### CODE REVIEW

**Comment by fredericDelaporte** [comment]
Switched to WIP because collection proxies may have the same trouble, according to this [comment](https://github.com/nhibernate/nhibernate-core/issues/1920#issuecomment-444568933).

**Comment by fredericDelaporte** [comment]
I do not see how we could "get" a collection without having it previously loaded as an uninitialized proxy, but I still have changed in the same way its loading logic. (The nearer to a "get" for a collection would be an entity load with a collection fetch, but that does not trigger batching.)

**Comment by RogerKratz** [comment]
I was about to suggest writing a test for "collection case", but reading your last comment I understand this change was just "a safety net", right?

**Comment by fredericDelaporte** [comment]
> I was about to suggest writing a test for "collection case", but reading your last comment I understand this change was just "a safety net", right?

Yes. There is no `ISession.Get` equivalent for collections. But maybe, for example, some `Merge` cases could trigger the same issue. I do not know. Having a test case for collections would be better, if it is actually possible. But I am not sure it is.

**Comment by RogerKratz** [comment]
Great! Thanks!

**Comment by maca88** [comment]
@RogerKratz thanks for the provided test! It's my bad that I didn't tested this scenario.
@fredericDelaporte the provided fix is not correct as it can cause an endless loop where the `entityKeys` would be checked over and over again. 
I've added additional checks in #1925 to prevent that and additional tests.

**Comment by fredericDelaporte** [comment]
Better add them here I think. It would have avoided to lose the improvements already done here, like generating the async tests for GH1920 tests (and some white-space cleanup in them).

**Comment by maca88** [comment]
I've made a [PR](https://github.com/RogerKratz/nhibernate-core/pull/1).

**Comment by fredericDelaporte** [comment]
Indeed, you are not among NHibernate "members".

**Comment by fredericDelaporte** [comment]
Replaced by #1925.

**Pull request closed without merging**
