### PR TITLE
Additional check if child session has already been closed.

### PR DESCRIPTION
**Pull request by itmagination**
This simple fix prevents unnecessary `SessionException("Session was already closed")` throw when both parent session and child session are closed separately (order does not matter). Before invoking close on child session (during parent session close) we should check if child session has not been closed already. Unfortunately to check if session was closed we have to use `SessionImpl` class instead of `ISession` interface, so we changed `SessionImpl`’s `childSessionsByEntityMode` private field type `IDictionary<EntityMode, ISession>` into `IDictionary<EntityMode, SessionImpl>`.

### CODE REVIEW

**Comment by hazzik** [comment]
Please use `ISessionImplementor` instead of SessionImpl

**Comment by itmagination** [comment]
I used `ISessionImplementor` instead of `SessionImpl` as requested. Unfortunately I had to add `Close` method in `ISessionImplementor` interface and make other necessary changes in dependent types (add abstract `Close` method in `AbstractSessionImpl` etc.). In `GetSession` method of `SessionImpl` class I had to cast result to `ISession` interface, because there is no formal connection between `ISession` and `ISessionImplementator` interfaces.

**Comment by hazzik** [comment]
Hi @itmagination.

There is `ISession.IsOpen` property which implementation is exactly `!IsClosed`, so, this change shall be only one line:

```
if (pair.Value.IsOpen)
{
     pair.Value.Close();
}
```

No other changes are required.

**Comment by itmagination** [comment]
Oh my! You're right! I've closed this knotty PR and opened a new one #542 containing this simple fix. Thank you!

**Pull request closed without merging**
