### PR TITLE
NH-3784, NH-3785 - Improvements to handling collection filtering

### PR DESCRIPTION
**Pull request by dmitryvk**
This PR fixes NH-3784, NH-3785.

Also it removes some cruft from HqlSqlWalker (it was modifying input AST while processing filter) - preprocessing of "filter-implied FROM" is now handled before HqlSqlWalker.

### CODE REVIEW

**Comment by hazzik** [comment]
Nicely done, thanks.

**Comment by hazzik** [comment]
@dmitryvk could you please squash your pull request?

**Comment by dmitryvk** [comment]
Sure, I'll do that. (I also spotted a typo: AddImpliedForm instead of AddImpliedFrom, I'll fix that too).

**Comment by dmitryvk** [comment]
Squashed commits

**Pull request merged**
