### PR TITLE
NH-3990 - Install Microsoft.VisualBasic package to enable compilation of NH-3302 tests

### PR DESCRIPTION
**Pull request by hazzik**
- Also remove auto-generated junk

### CODE REVIEW

**Comment by hazzik** [comment]
@ngbrown please take a brief look.

**Comment by ngbrown** [comment]
[Remotion.Linq 2.2.0-alpha-004](https://www.nuget.org/packages/Remotion.Linq/2.2.0-alpha-004) is available too, but I haven't had a chance to update to it and test yet.

**Comment by hazzik** [comment]
@ngbrown re-linq is till next time. This is about VB's like operator. Can you please check that your .NET Core build works with this change?

**Comment by ngbrown** [comment]
LGTM. Compiles and runs fine on my computer.

I removed the ignore, and tried it, and Like still isn't supported.

**Comment by hazzik** [comment]
Yes, like isn't supported. This is about compilation.

**Pull request merged**
