### PR TITLE
merged entity's properties related arrays (propertyNames, propertyTyp…

### PR DESCRIPTION
**Pull request by usarskyy**
…es, etc): all arrays alias main "properties" array

Public interface of EntityMetamodel remains unchanged.

### CODE REVIEW

**Comment by usarskyy** [comment]
Hi everyone,

can somebody review my changes? It's been awhile since I pushed them.
As you can see, they are not so sophisticated. I was mainly focused on simplifying debugging and refactoring process. All public interfaces remain unchanged.
BTW, I can also remove outdated variables, that I keep for backward compatibility, if you decide to include those changes in NH v5.

**Comment by gliljas** [comment]
Hi and thanks!

Have you evaluted the performance implications of using this approach, since it uses a lot more iterations over the properties? I agree that it makes the code clearer, which may be worth a bit of an impact in the right phase.

**Comment by usarskyy** [comment]
Hi!

Yes, I did. Actually, current implementation does not have performance issues because all arrays are still there. They are just lazy-evaluated. My target is to remove them at all and I even did application profiling to check the performance without arrays but unfortunately did not record the results.
If you give me a bit of time, I can run profiling once more and prepare a small report.

**Comment by fredericDelaporte** [comment]
We need a [Jira](https://nhibernate.jira.com) for keeping track of changes and releasing, could please add one?

**Comment by bahusoid** [comment]
I don't quite understand the title as I don't see any  "merged entity's properties related arrays".

And I don't think that making all arrays lazy can be considered as improvement - as it involves locking on initialization and in general works slower. IMHO it's not worth it here.  Shall we close it?

**Comment by fredericDelaporte** [comment]
It seems the aim was to remove all these arrays, but the PR was not there yet.

**Comment by hazzik** [comment]
Ok, closing.

**Pull request closed without merging**
