### PR TITLE
add NumericalScale to IColumnMetadata 

### PR DESCRIPTION
**Pull request by podzyuban**
1) add NumericalScale to IColumnMetadata 
2) Read NumericalScale in Ms…SqlColumnMetadata 
3) unitTest

### CODE REVIEW

**Comment by podzyuban** [comment]
Hi.
I think it test problem.
For example, Nhibernate SQL Server ODBC failedTest 'FooBarTest.' 
He has exception: ' ----> System.Data.Odbc.OdbcException : ERROR [22008] [Microsoft][SQL Server Native Client 11.0]Datetime field overflow. Fractional second precision exceeds the scale specified in the parameter binding.
 TearDown : Test didn't clean up after itself. session closed: True database cleaned: False connection closed: True'.
In my opinion it test problem.

**Comment by hazzik** [comment]
@podzyuban don't worry about these 3 failing tests runs.

**Comment by oskarb** [comment]
Why this change? Is there a bug report/feature request in Jira to explain the problem/benefit?

**Comment by hazzik** [comment]
Thanks for the contribution @podzyuban. However, I'm not going to accept it without further explanation why this is required.

**Pull request closed without merging**
