### PR TITLE
Multi-Level Distinct Entity Transformer 

### PR DESCRIPTION
**Pull request by manarhusrieh**
This transformer is similar to DistinctRootEntityTransformer but removes
duplicates from all the details of the entity.

### CODE REVIEW

**Comment by hazzik** [comment]
@manarhusrieh what is the difference to #228?

**Comment by fredericDelaporte** [comment]
I think I have understood the differences from its description (not read the code). This one not only perform a distinct on listed entities, but also on any children entity which may be listed twice in an collection belonging to the same root entity.

This could serve as a workaround for hiding the effects of a Cartesian product occurring when eager fetching more than one children collections. But well, this will not solve the performance trouble such a Cartesian product causes.

**Comment by hazzik** [comment]
Can you please enable [Allow edits from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) PR option?

**Comment by fredericDelaporte** [comment]
Thinking again about this result transformer, I do not think we should accept it.
It is a result transformer which mutates entity states, by altering the contents of entity collections. It may cause undesired updates. I do not think a result transformer which mutates entity collections should be accepted.

If the aim is to use it as a workaround for the Cartesian product troubles occurring when fetching multiple collections, another solution should be chosen instead, like using multiple queries or futures to separate the fetches while batching them in a single roundtrip to the database, as illustrated in the last example of multi-queries [here](http://nhibernate.info/doc/nhibernate-reference/performance.html#performance-multi-query).

**Comment by fredericDelaporte** [comment]
The number of elements in the collection does change, right? That is a mutation of the collection, and this will cause the collection to be persisted on flush. By the way another workaround would be to map them as `set`. But performance wise it is not a very good workaround since the Cartesian product will still occur: separating the fetches of different collections would still be better.

**Comment by manarhusrieh** [comment]
I didn't about the working of the collections in sessions. I usually use this transformer with read-only result sets, that is why I didn't run into this problem before.
Thanks

**Pull request closed without merging**
