### PR TITLE
NH-4082 Load virtual assembly for mapping

### PR DESCRIPTION
**Pull request by Triflepl**
Ok, i make an contribution for master version.

### CODE REVIEW

**Comment by fredericDelaporte** [comment]
Thanks,
So this is indeed [NH-4080](https://nhibernate.jira.com/browse/NH-4080), and replaces #701.
I should have thought about it on your first PR: there is no tests. We need tests for merging a PR. May you add relevant tests?

Regards.

**Comment by Triflepl** [comment]
Sorry about that.
I can't edit commit version on jira request, so i was thinking that different version of commit it will need a different jira request. 
Ok, so i will add tests in \CfgTest\ because it is configuration new function.

**Comment by fredericDelaporte** [comment]
Great.
That is not a trouble to have history of proposed commit on the Jira. It distinguishes between merged ones and others.

**Comment by Triflepl** [comment]
So i need too change that commit NH-4082 to NH-4080 in my repository for nice look history.

**Comment by fredericDelaporte** [comment]
Replace by #705.

**Pull request closed without merging**
