### PR TITLE
NH-3488 - Strongly typed DML

### PR DESCRIPTION
**Pull request by hazzik**
This is a rewrite of #391 

Following syntax is supported:

#### Delete
No changes here
````
s.Query<Dog>().Where(x=>x.Name == "Jack").Delete();
````
#### Update
Syntax with `.As(x=>new ...)`/`.Assign(x => x.Set(...))` has been removed
```
s.Query<Dog>().Where(x=>x.Name == "Jack").Update(x=>new Dog { Age=Age+1 });
```
#### Insert
Syntax with `.As(x=>new ...)`/`.Assign(x => x.Set(...))` has been removed
```
s.Query<Cat>().Where(x=>x.Name="Puss").Insert(x=>new Dog { Name="Jack", Friend=x });
```
### TODO:
- [x] Update documentation
- [ ] ? Do not rewrite expression into dictionary
- [ ] Allow anonymous types
  - In order to support UPDATE for abstract classes and protected member, I think we need to add support to write following
    ``` s.Query<Animal>().Update(x=>new { Name = "Tiger" }); ```

/cc @fredericDelaporte @gliljas

### CODE REVIEW

**Comment by gliljas** [comment]
I like the cleanup, but the removal of the syntax worries me. It was put there for a reason. Requiring a "new X" makes it necessary to use a real constructor, and that may not be possible in all scenarios. When it's possible, it's convenient, as just one little ".As" away.

/G

**Comment by hazzik** [comment]
@gliljas I have plans to add support for anonymous types for these cases (see the 3rd point in a TODO). Also, I was thinking about Dictionary instead of anonymous types.

**Comment by fredericDelaporte** [comment]
It looks nicer to me this way too, good job.

I think the anonymous/dictionary syntax would be needed for insert too. But that would cause the generic type argument to be mandatory for it to works.

**Comment by hazzik** [comment]
Closed in favor of #391

**Pull request closed without merging**
