### PR TITLE
Short-Circuit SessionFactoryImpl.Close() when already closed

### PR DESCRIPTION
**Pull request by albertodall**
Fixes Issue #2193

### CODE REVIEW

**Comment by hazzik** [comment]
Hi, it seems that this requires async regenration. Could you please check [CONTRIBUTING.md](https://github.com/nhibernate/nhibernate-core/blob/master/CONTRIBUTING.md) how to do async code regenerations.

**Comment by albertodall** [comment]
Hi @hazzik
You're right, I forgot this task...
I tried to regenerate the async code following the contribution guidelines, but I'm getting some errors:
[loadtasks] Failure scanning "C:\Users\Alby\Source\nhibernate-core\Tools\nant\bin\NAnt.NUnit2Tasks.dll" for extensions. Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

generate-async:

     [exec] 08:30:54,558 INFO  CommandLine:0 - AsyncGenerator
     [exec]
     [exec] 08:30:54,790 INFO  AsyncCodeGenerator:0 - Generating async code started
     [exec] 08:30:55,018 FATAL CommandLine:0 - System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
     [exec]    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
     [exec]    at System.Reflection.RuntimeAssembly.get_DefinedTypes()
     [exec]    at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
     [exec]    at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
     [exec]    at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
     [exec]    at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
     [exec]    at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
     [exec]    at Microsoft.CodeAnalysis.Host.Mef.DesktopMefHostServices.get_DefaultServices()
     [exec]    at AsyncGenerator.AsyncCodeGenerator.CreateWorkspace(String targetFramework)
     [exec]    at AsyncGenerator.AsyncCodeGenerator.<GenerateAsync>d__0.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at AsyncGenerator.CommandLine.Program.Main(String[] args)

BUILD FAILED

**Comment by hazzik** [comment]
Hibernate has a lock around `isClosed`. Do we want it, @fredericDelaporte, @bahusoid?

**Comment by bahusoid** [comment]
> Hibernate has a lock around isClosed. Do we want it?

I see no harm without it. So I would say no.

**Comment by fredericDelaporte** [comment]
The lock is consistent with the principle that once created, a session factory is a thread safe object. So it is more valid to have it, in order to guarantee that even if the close method is called concurrently, only one closing will occur.
Still this looks to me as quite a corner case. Destroying the same object concurrently is of little use, I do not see much value in supporting this.

**Comment by hazzik** [comment]
Ok

**Comment by hazzik** [comment]
Ok

**Comment by hazzik** [comment]
Ok

**Pull request merged**
