### PR TITLE
Fix gh3113

### PR DESCRIPTION
**Pull request by fredericDelaporte**
Minimal fix proposal for #3113, which is a 5.3.0 regression introduced by #2327 along with #2025.

This trouble does by the way demonstrate that we lack an automated tests run for dialects using only theta style joins. Hundreds of tests fail for such a dialect, and maybe there is a bunch of them which are regressions.

### CODE REVIEW

**Review by hazzik — APPROVED** [review]

**Comment by fredericDelaporte** [comment]
Before merging, I have to compare a test run on Oracle8i dialect without the change to one with the change, in order to make sure it does not break anything new.

**Review by bahusoid — APPROVED** [review]

**Comment by fredericDelaporte** [comment]
Here are the test results. Down from 563 failures to 511, no new failure seen. (But checked manually.)
[Test-Results.zip](https://github.com/nhibernate/nhibernate-core/files/9448403/Test-Results.zip)

A test run on 5.2.x have "only" an hundred failures or so, with maybe 2 000 less tests. I think there is quite a bunch of other regressions for Oracle8i in 5.3.x, but it is a bit tedious to detect manually which tests are newly failing.

**Comment by hazzik** [comment]
I think "we do not care" and should deprecate all older Oracle dialects.

**Comment by fredericDelaporte** [comment]
I should have rewritten the commit message a bit better, sorry for having overlooked this.

**Pull request merged**
