### PR TITLE
Test case and fix for NH-3079 on branch 3.4

### PR DESCRIPTION
**Pull request by hailtondecastro**
Test case and fix for NH-3079 on branch 3.4

### CODE REVIEW

**Comment by hailtondecastro** [comment]
Pull request posted on 
https://nhibernate.jira.com/browse/NH-3079?focusedCommentId=39554&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-39554

**Comment by hazzik** [comment]
Can you please enable [Allow edits from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) PR option?

**Comment by hailtondecastro** [comment]
Done. Sorry for the delay.

**Comment by hailtondecastro** [comment]
I enabled this on #452 as well.
Thanks.

**Comment by hazzik** [comment]
We do not plant to support 3.4.x at the moment

**Pull request closed without merging**
