### PR TITLE
Allow Linq Query to load entities as read-only

### LINKED ISSUE #908: NH-3470 - Allow Linq Query to load entities as read-only
**Dan Plaskon** created an issue — <time datetime="2013-05-30T14:54:22.517Z" title="2013-05-30T14:54:22.517Z">30th May 2013, 14:54:22</time>:
> For example, using QueryOver you can use:
> 
> `Session.QueryOver<Foo>().ReadOnly()`
> 
> It would be great to have an equivalent method available when loading entities with the linq provider; something along the lines of:
> 
> `Session.Query<Foo>().AsReadOnly()`
> 
---
**Ricardo Peres** added a comment — <time datetime="2014-03-14T10:15:46.773Z" title="2014-03-14T10:15:46.773Z">14th March 2014, 10:15:46</time>:
> Pull request: https://github.com/nhibernate/nhibernate-core/pull/260
> 
---
**Ricardo Peres** added a comment — <time datetime="2014-09-09T08:09:02.416Z" title="2014-09-09T08:09:02.416Z">9th September 2014, 8:09:02</time>:
> Duplicates NH-3658
> 
---
**Ricardo Peres** added a comment — <time datetime="2014-11-20T17:46:22.463Z" title="2014-11-20T17:46:22.463Z">20th November 2014, 17:46:22</time>:
> Pull request included in issue NH-2140.
> 
---
**Ricardo Peres** added a comment — <time datetime="2015-04-16T08:13:08.682Z" title="2015-04-16T08:13:08.682Z">16th April 2015, 8:13:08</time>:
> New pull request: https://github.com/nhibernate/nhibernate-core/pull/418
> 
---
**Alexander Zaytsev** added a comment — <time datetime="2016-08-12T04:40:11.661Z" title="2016-08-12T04:40:11.661Z">12th August 2016, 4:40:11</time>:
> Move unresolved improvements and new features with minor and trivial priorities to 4.2.0
> 
---
**Frédéric Delaporte** added a comment — <time datetime="2017-04-19T17:32:12.968Z" title="2017-04-19T17:32:12.968Z">19th April 2017, 17:32:12</time>:
> If NH-3987 gets done, this improvement will depend on it.
> 
---
**Alexander Zaytsev** added a comment — <time datetime="2017-09-14T01:47:17.111Z" title="2017-09-14T01:47:17.111Z">14th September 2017, 1:47:17</time>:
> Move issues from 4.2 to 5.0
> 
---
**Alexander Zaytsev** added a comment — <time datetime="2017-09-14T01:50:03.001Z" title="2017-09-14T01:50:03.001Z">14th September 2017, 1:50:03</time>:
> Move new features to 5.1
>

### PR DESCRIPTION
**Pull request by hazzik**
Fixes #908 ([NH-3470](https://nhibernate.jira.com/browse/NH-3470))

### CODE REVIEW

**Comment by hazzik** [comment]
Done. Also added XML comments.

**Comment by hazzik** [comment]
Please don’t merge yet. I want to make another adjustment.

**Comment by hazzik** [comment]
Done

**Comment by hazzik** [comment]
Done

**Comment by vincentparrett** [comment]
Is there going tobe another release soon with this included? 5.04?

**Comment by vincentparrett** [comment]
I just realised this is tagged as 5.1 - any ideas on a5.1 release date?

**Comment by fredericDelaporte** [comment]
Sorry, no ETA.

**Pull request merged**
