### PR TITLE
Ingres9 sequences

### PR DESCRIPTION
**Pull request by gamblen**
Support for Sequence use within Ingres

### CODE REVIEW

**Comment by oskarb** [comment]
https://nhibernate.jira.com/browse/NH-3921

**Comment by oskarb** [comment]
Closing this. I've submitted a cleaned version as PR #529.

**Comment by oskarb** [comment]
@gamblen The cleaned up code is in PR #529, but it fails some tests. Please have a look at fixing that.

**Comment by gamblen** [comment]
@oskarb I have got PR#529 and it builds ok.  I cannot access the TeamCity details on why they are failing to build, but I cannot imagine how adding a couple of changes to the Ingres9 Dialect can make the builds fail for unrelated databases.  I am unsure how to proceed.

**Comment by oskarb** [comment]
Have you executed all the tests? It's a common test that's failing. ( I'm
away from computer right now and don't remember the name.)

Den 4 dec. 2016 2:35 em skrev "Nic Gamble" <notifications@github.com>:

@oskarb <https://github.com/oskarb> I have got PR#529 and it builds ok. I
cannot access the TeamCity details on why they are failing to build, but I
cannot imagine how adding a couple of changes to the Ingres9 Dialect can
make the builds fail for unrelated databases. I am unsure how to proceed.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nhibernate/nhibernate-core/pull/439#issuecomment-264707387>,
or mute the thread

**Comment by gamblen** [comment]
@oskarb Yes, there were plenty of failures, mostly all unable to connect to a MSSQL database.  I am currently on a laptop with no DB's installed, so possibly cannot see the wood for the trees..  There is no steps in the ShowMenuBuild.bat that will setup for Ingres.  Would that need to be done?

**Comment by oskarb** [comment]
@gamblen Let's continue the discussion in #529.

**Pull request closed without merging**
