### PR TITLE
NH-4073 - Replace NHibernate.Web.Example with modern version.

### PR DESCRIPTION
**Pull request by ngbrown**
This is [NH-4073](https://nhibernate.jira.com/browse/NH-4073)

### CODE REVIEW

**Comment by hazzik** [comment]
Some white spaces are inconsistent

**Comment by ngbrown** [comment]
@hazzik It's because the templates started out at 4 space characters, but the `.editorconfig` dictates tabs for any new lines I create, and then GitHub shows tabs as 8 spaces.

Is the solution to convert every file to tabs then?  Can I set *.cshtml and *.json to 2 character spaces in `.editorconfig`?

**Comment by hazzik** [comment]
Yes, `.editorconfig` would work. I think the options shall be as following:
.xml: spaces, 2 spaces
.json: spaces, 2 spaces
.cshtml: spaces, 4 spaces

**Comment by ngbrown** [comment]
Fixed.

Evidently one can set the hard-tab width in GitHub by setting the `indent_size` in `.editorconfig`.  https://github.com/isaacs/github/issues/170#issuecomment-150489692  But then you wouldn't see when I screw it up. 😄

**Pull request merged**
