### PR TITLE
Fix Contains subquery with parameter

### LINKED ISSUE #3218: Bug 'Could not execute query' after updating to v5.3.11 or higher
I tried to update NHibernate from version v5.3.3 to v5.4 and I noticed that until v.5.3.10, the following code worked fine:

```c#
var integralPlans = _repository.Queryable<IntegralPlan>()
    .Where(_ => _.Clients.Select(_ => _.Id).Contains(clientId))
    .OrderByDescending(_ => _.CreatedOn)
    .ToList();
```

But since v5.3.11, in that line I get an exception, with the following message:

```json
{"Unable to cast object of type 'System.Guid' to type 'Contoso.ProjectName.Domain.Client'."}
```

The generated query is:

```
could not execute query
[ select integralpl0_.id as id1_202_, integralpl0_.changedBy as changedby2_202_, integralpl0_.changedOn as changedon3_202_, integralpl0_.createdBy_id as createdby4_202_, integralpl0_.createdOn as createdon5_202_, integralpl0_.dossierEntry_id as dossierentry6_202_, integralpl0_.entityNumber as entitynumber7_202_, integralpl0_.integralPlanTemplate_id as integralplantemplate8_202_, integralpl0_.status_id as status9_202_ from integralPlan integralpl0_ where exists (select client2_.id from integralPlan_clients clients1_, client client2_ where integralpl0_.id=clients1_.integralPlan_id and clients1_.client_id=client2_.id and client2_.id=?) order by integralpl0_.createdOn desc ]
  Name:p1 - Value:71460036-73dd-4f22-1234-633143769ac7 [Type: NHibernate.Type.ManyToOneType(Contoso.ProjectName.Domain.Client)]
[SQL: select integralpl0_.id as id1_202_, integralpl0_.changedBy as changedby2_202_, integralpl0_.changedOn as changedon3_202_, integralpl0_.createdBy_id as createdby4_202_, integralpl0_.createdOn as createdon5_202_, integralpl0_.dossierEntry_id as dossierentry6_202_, integralpl0_.entityNumber as entitynumber7_202_, integralpl0_.integralPlanTemplate_id as integralplantemplate8_202_, integralpl0_.status_id as status9_202_ from integralPlan integralpl0_ where exists (select client2_.id from integralPlan_clients clients1_, client client2_ where integralpl0_.id=clients1_.integralPlan_id and clients1_.client_id=client2_.id and client2_.id=?) order by integralpl0_.createdOn desc]
```

Looks like the p1 value is not placed in the generated query, but a ? appears in its place.

### PR DESCRIPTION
**Pull request by bahusoid**
Fixes #3218

### CODE REVIEW

**Review by fredericDelaporte — APPROVED** [review]
> It started working by chance for your case in 5.3 due to other bug :)

So, should we consider this a regression having happen in 5.3, and then should we target 5.3.x instead?

**Comment by bahusoid** [comment]
Yes, we should backport it to 5.3. But what's the plan? Didn't we simply cherry-pick changes for older branches in separate PR?
Or are you planning on 5.3 -> 5.4 -> master merge?

**Comment by fredericDelaporte** [comment]
If the fix can target 5.3.x "as is" and be simply merged to 5.4.x, it is then easier to target 5.3.x. If 5.3.x needs a different fix, better target 5.4.x and backport.

**Comment by bahusoid** [comment]
> it is then easier to target 5.3.x

Done

**Review by fredericDelaporte — APPROVED** [review]

**Comment by bahusoid** [comment]
Need to check one more case (will add test later)

**Pull request merged**
