### PR TITLE
Add Firebird 4 dialect

### LINKED ISSUE #3165: Improve support for Firebird 4
Currently there is a couple of tests that fail for Firebird 4.

### PR DESCRIPTION
**Pull request by hazzik**
TODO:
- [x] Fix tests
- [x] Run both Firebird 3 and Firebird 4

Fixes #3165

### CODE REVIEW

**Comment by hazzik** [comment]
21 (+19 async) tests currently fail

Changes of `CURRENT_TIMESTAMP`:

> `LOCALTIMESTAMP` was introduced in Firebird 3.0.4 and Firebird 2.5.9 as a synonym of `CURRENT_TIMESTAMP`. In Firebird 4.0, `CURRENT_TIMESTAMP` returns a `TIMESTAMP WITH TIME ZONE` instead of a `TIMESTAMP [WITHOUT TIME ZONE]`, while `LOCALTIMESTAMP` returns `TIMESTAMP [WITHOUT TIME ZONE]`. It is recommended to use `LOCALTIMESTAMP` when you do not need time zone information.

https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref40/fblangref40-contextvars-localtimestamp.html

Failing tests:
* NHibernate.Test.DialectTest.DialectFixture.CurrentTimestampSelection
* NHibernate.Test.DialectTest.MsSqlDialectFixture.CurrentTimestampSelection
* NHibernate.Test.Hql.HQLFunctions.Current_TimeStamp
* NHibernate.Test.Linq.PreEvaluationTests(False,False).CanSelectDateTimeNow
* NHibernate.Test.Linq.PreEvaluationTests(False,True).CanSelectDateTimeNow

**Comment by hazzik** [comment]
@fredericDelaporte, @bahusoid should we just register `CURRENT_TIMESTAMP` as `LOCALTIMESTAMP` and `CURRENT_TIMESTAMP_OFFSET` as `CURRENT_TIMESTAMP`? In other words, do we want to keep compatibility with FB3 < 3.0.2 and FB2 < 2.5.9?

Or we create Firebird4Dialect with this mapping?

**Comment by fredericDelaporte** [comment]
It sounds safer to me to create a Firebird4Dialect overriding these. No risk of of breaking changes for application running on older Firebird, and a quite natural way to fix these types for those having upgraded to Firebird4.

**Comment by bahusoid** [comment]
Both dialects now fail with single test:
1) Failed : NHibernate.Test.Tools.hbm2ddl.SchemaMetadataUpdaterTest.SchemaMetadataUpdaterFixture.EnsureReservedWordsHardCodedInDialect
  Expected: equivalent to < "active", "add", "admin", "after", "all", "alter", "and", "any", "as", "asc"... >
  But was:  < "active", "add", "admin", "after", "all", "alter", "and", "any", "as", "asc"... >
  Missing (44): < "bit_length", "boolean", "char_length", "character_length", "comment", "corr", "covar_pop", "covar_samp", "current_connection", "current_transaction"... >
   at NHibernate.Test.Tools.hbm2ddl.SchemaMetadataUpdaterTest.SchemaMetadataUpdaterFixture.EnsureReservedWordsHardCodedInDialect() in /home/runner/work/nhibernate-core/nhibernate-core/src/NHibernate.Test/Tools/hbm2ddl/SchemaMetadataUpdaterTest/SchemaMetadataUpdaterFixture.cs:line 112

**Review by bahusoid — DISMISSED** [review]
Looks good except:
> This branch has conflicts that must be resolved

**Comment by hazzik** [comment]
Resolved

**Review by bahusoid — APPROVED** [review]

**Pull request merged**
