### PR TITLE
NH-3903: TableGenerator quotes table and column names.

### PR DESCRIPTION
**Pull request by jan-schubert**
https://nhibernate.jira.com/browse/NH-3903

### CODE REVIEW

**Comment by oskarb** [comment]
Looks good, but can you please fix the indenting in TableGenerator to match the surrounding indent style?

NHibernate generally uses tabs for indent, and space for alignment. Consider using Resharper and EditorConfig to have VS automatically pick up on NHibernate's configured style.

**Comment by oskarb** [comment]
The corresponding change in Hibernate is bit more full-featured:
Corresponding issue for Hibernate: https://hibernate.atlassian.net/browse/HHH-4553
Their commit: https://github.com/hibernate/hibernate-orm/commit/a2bf14ae7c2ed7b2b0a6eb558dad08bcfc69c489

Later on, they've also deprecated and then removed the TableGenerator and there are lots of changes around the id generators. Would be interesting to port a larger piece.

**Comment by jan-schubert** [comment]
Sorry but I have not enough time to develop the full featured change, currently.

I hope you integrate my pull request for the next release. We need it to deploy our next software release.

**Comment by oskarb** [comment]
The patch, as is, means that the NHibernate.Id modules takes a dependency on NHibernate.Mapping, which it doesn't currently have. Futhermore, NHibernate.Mapping does already have a dependency on NHibernate.Id.

Not sure which direction is best, but making it cyclic isn't good.

**Comment by oskarb** [comment]
Sorry, but I don't want to accept this as is. I will nominate the bug for for NH5.0 in the hopes that a better fix can be provided. In the meantime you can use a custom build.

The test cases from this PR should be useful.

**Pull request closed without merging**
