### PR TITLE
NH-3845, NH-3946 - Fix Linq queries with `.OfType<T>()` and `where is T`, where T is a mapped base type

### PR DESCRIPTION
**Pull request by alexDevBR**
Patch allows queries like `session.Query<Animal>().Where(x => x is Mammal)` and `session.Query<Animal>().OfType<Mammal>()` to get all dogs and cats, for example.

### CODE REVIEW

**Comment by hazzik** [comment]
Related to #456. Maybe the logic shall be combined.

**Comment by fredericDelaporte** [comment]
@hazzik 

> I've hijacked your PR to also (partially) fix NH-3845

Should we re-open NH-3845 (auto-resolved by merging this PR) and move it to 5.1.0?

**Comment by hazzik** [comment]
Yes

**Comment by hazzik** [comment]
@fredericDelaporte no, I've extracted the not fixed cases into [NH-3947](https://nhibernate.jira.com/browse/NH-3947)

**Pull request merged**
