### PR TITLE
NH-3454 - Release event handler to facilitate garbage collection

### PR DESCRIPTION
**Pull request by flcdrg**
Release the event handler attached in AdoNetWithDistributedTransactionFactory so that item can be garbage collected successfully.

https://nhibernate.jira.com/browse/NH-3454

### CODE REVIEW

**Comment by hazzik** [comment]
@flcdrg did you have chance to rebase?

**Comment by flcdrg** [comment]
Sorry no, I haven't yet. It's sitting on my "list of things to do" so I
haven't forgotten :-)

**Comment by hazzik** [comment]
Ok, no worries.

**Comment by hazzik** [comment]
@flcdrg any news?

**Pull request closed without merging**
