### PR TITLE
NH-3911 - Fixed InvalidCastException in ReflectionOptimizer

### PR DESCRIPTION
**Pull request by LordJZ**
Fixes #511

### CODE REVIEW

**Comment by oskarb** [comment]
See comment on #511.

**Comment by LordJZ** [comment]
I've been able to simplify the test case and added a brief description. Rebased and force pushed. Please see how you like it. Old branch available here: https://github.com/LordJZ/nhibernate-core/tree/nh-3911-old

P.S. That "someone else committed to your repository" notification caught me by surprise and kept me aware for an hour tonight. :)

**Comment by hazzik** [comment]
Nice:)

**Comment by hazzik** [comment]
Hi @LordJZ can you please enable [Allow edits from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) feature?

**Comment by LordJZ** [comment]
@hazzik it is enabled though. That's how you pushed to my repo [earlier](https://github.com/LordJZ/nhibernate-core/commits/nh-3911-old).

**Comment by hazzik** [comment]
You're right. Thanks.

**Comment by hazzik** [comment]
Thanks, it has been merged

**Pull request merged**
