### PR TITLE
WIP - Merge 5.2.x

### PR DESCRIPTION
**Pull request by fredericDelaporte**
Done as a pull request on a dedicated branch to solve conflicts and regen async if possible. I guess having cherry-pick a commit from master is the conflict source.

### CODE REVIEW

**Comment by fredericDelaporte** [comment]
I tend to think this should be merged by rebasing the merge commit and the async regen on master, but I am unsure "Rebase and merge" would do this. Maybe I would have better re-doing the merge then async regen directly on master.

**Comment by fredericDelaporte** [comment]
About "Include backports release notes", maybe it would be better to add first that commit on 5.2.x directly then merge.

**Comment by fredericDelaporte** [comment]
WIP - I will redo a single merge once 5.2.5 is done.

**Comment by hazzik** [comment]
>I am unsure "Rebase and merge" would do this. 

It will not. I think this has to be merged manually.

**Comment by fredericDelaporte** [comment]
Merge done directly

**Pull request closed without merging**
