### PR TITLE
 Use a statically resolved dialect when building the session factory 

### PR DESCRIPTION
**Pull request by fredericDelaporte**
This change is more a trivial optimization: when building the session factory, the dialect has no reason to change, and so we can use the same dialect instance from the start of the process to its end.
#1951, merged in v5.3, was already doing most of the work, by supplying to the built session factory an `IMapping` resolving the dialect at instantiation rather than dynamically.

This PR cherry-pick #1951 into 5.2.x, and furthermore switch `Configuration.mapping` member to the mapping having a static dialect, for the duration of the build.

So if anything does use the `mapping.Dialect` in steps prior to factory instantiation, it will now use that static one instead of instantiating it.

Well, that does probably not actually optimize anything in most cases as far as I know.

But it allows to restore a hack used by NHibernate.Spatial, which relies on having its dialect instantiated early in the factory building process. Without that hack, Spatial users cannot upgrade to NHibernate 5.2.x.
See nhibernate/NHibernate.Spatial#104.

That is why I issue this PR, targeting the 5.2.x branch.

### CODE REVIEW

**Comment by hazzik** [comment]
I don't think this will help spatial, the error happens long before `BuildSessionFactory` call.

**Comment by hazzik** [comment]
Ok, I've checked the stack trace. It should work.

**Comment by fredericDelaporte** [comment]
I had checked with a locally generated NuGet package with those changes, and an upgraded Spatial.

Still, @peetw, can you also check this change solves nhibernate/NHibernate.Spatial#104, just to be sure? Releasing a patch takes some time, so it is better to double check.

**Comment by hazzik** [comment]
Could you also include the release notes in the PR?

**Comment by peetw** [comment]
Thank you both for looking into this - much appreciated! I was away for the weekend so apologies for not replying sooner. I should have some time today to test whether the PR fixes the issue.

**Comment by fredericDelaporte** [comment]
> Could you also include the release notes in the PR?

I have not put them directly due to not having definitely decided what to do for #1983 (but most likely I will just add a possible breaking change notice), and also due to the suspected regression on `not-found` discussed in off-topic comments of #1995. If there is actually a regression there, it would then be better to fix it in 5.2.4 too.

**Comment by peetw** [comment]
@fredericDelaporte Using the NuGet package from the [build artifacts](https://teamcity.jetbrains.com/viewLog.html?buildId=1982568&buildTypeId=NHibernate_NHibernateReleasePackage&tab=artifacts#%2FNHibernate-5.2.3%2Fnuget_gallery), I have confirmed that this PR fixes the issue reported in [nhibernate/NHibernate.Spatial#104](https://github.com/nhibernate/NHibernate.Spatial/issues/104) - thanks!

**Comment by fredericDelaporte** [comment]
Release commit added, adding by the way a lacking possible breaking change.

**Comment by hazzik** [comment]
The issue type has to be bug or task. Let’s call it bug.

**Comment by fredericDelaporte** [comment]
I have adjusted the releasenotes file accordingly.

**Comment by fredericDelaporte** [comment]
Release commit dropped.

**Pull request merged**
