### PR TITLE
Avoid double proxy casting

### PR DESCRIPTION
**Pull request by bahusoid**
By adding `bool IsProxy(object entity, out INHibernateProxy proxy)` to `IProxyFactoryFactory`

### CODE REVIEW

**Comment by hazzik** [comment]
I don't see how it avoids double casting at this moment. I can clearly see how that would avoid this in 6.0, but now its just a mess. Does it worth it now? 

Honestly, I would prefer abolish "IsProxy" method in its entirety. It was added as a some workaround for Spring.NET. And Spring.NET is dead now.

**Comment by bahusoid** [comment]
Ok. Closing for now

**Comment by bahusoid** [comment]
>  I would prefer abolish "IsProxy" method in its entirety.

Or should I obsolete `IsProxy` method now and replace its usages?

**Comment by hazzik** [comment]
No, it would be too soon. I'll create an issue.

**Pull request closed without merging**
