### PR TITLE
Fix SchemaValidator failing for PostgreSql sequences

### LINKED ISSUE #1163: NH-3545 - SchemaValidator fails for PostgreSql sequences
**Tomas Sedlak** created an [issue](https://nhibernate.jira.com/browse/NH-3545) — <time datetime="2013-10-01T14:31:20.074Z" title="2013-10-01T14:31:20.074Z">1st October 2013, 14:31:20</time>:
> When validating schema in PostgreSql 9.2 the SchemaValidator throws <NHibernate.HibernateException> = {"Missing sequence or table: permission*tree_id*gen"} exception.
> 
> To fix this issue I had to override QuerySequencesString in the PostgreSQL82Dialect class.
> 
> I created PostgreSQL92Dialect as a workaround for this issue.
> 
> 
---
**Alexander Zaytsev** added a comment — <time datetime="2013-10-01T21:16:23.983Z" title="2013-10-01T21:16:23.983Z">1st October 2013, 21:16:23</time>:
> <~mrjoe>, a test case or at least a stack-trace would be useful.
> 
---
**Tomas Sedlak** added a comment — <time datetime="2013-10-01T22:00:57.579Z" title="2013-10-01T22:00:57.579Z">1st October 2013, 22:00:57</time>:
> Added simple test case.
> 
---
**chris_x** added a comment — <time datetime="2014-01-28T12:39:08.967Z" title="2014-01-28T12:39:08.967Z">28th January 2014, 12:39:08</time>:
> Having the same problem with PostgreSQL 9.3, using NHibernate.Dialect.PostgreSQLDialect. Your workaround (using custom PostgreSQL92Dialect) works for me.
>

### PR DESCRIPTION
**Pull request by lillo42**
Fixes #1163

### CODE REVIEW

**Comment by hazzik** [comment]
@lillo42 hi. First of all thanks for the contribution. Unfortunately the PR has a lot of noise and also is outdated. Could you please avoid committing extra files and cleanup the PR to include only relevant changes?

**Comment by lillo42** [comment]
@hazzik the *.xml file ? I removed.

**Comment by hazzik** [comment]
I've changed selecting sequences to the method which works on 8.1 (due to the dialect being named PostgreSQL81Dialect). Also, I've removed irrelevant changes (converting methods and properties to lambda functions). Regenerated Async tests. And force-pushed.

**Comment by hazzik** [comment]
Moved to PostgreSQLDialect as it supported in every (?) version of the postgres

**Pull request merged**
