### PR TITLE
#2454 fix ConditionalProjection GetType from outer query

### LINKED ISSUE #2454: ConditionalProjection containing the correlation to outer query fails to determine projection type
Here is the code that causes the exception:

Entity classes:
```cs
	public class Project
	{
		public virtual Guid Id { get; set; }
		public virtual string Name { get; set; }
	}

	public class Component
	{
		public virtual Guid Id { get; set; }
		public virtual string Name { get; set; }
		public virtual Project Project { get; set; }
	}

	public class Tag
	{
		public virtual Guid Id { get; set; }
		public virtual string Name { get; set; }
		public virtual Component Component1 { get; set; }
		public virtual Component Component2 { get; set; }
	}
````

Mapping:
```cs
	mapper.Class<Project>(rc =>
	{
		rc.Id(x => x.Id, m => m.Generator(Generators.GuidComb));
		rc.Property(x => x.Name);
	});

	mapper.Class<Component>(rc =>
	{
		rc.Id(x => x.Id, m => m.Generator(Generators.GuidComb));
		rc.Property(x => x.Name);
		rc.ManyToOne(x => x.Project, m => { m.Column("ProjectId"); m.NotNullable(true); });
	});

	mapper.Class<Tag>(rc =>
	{
		rc.Id(x => x.Id, m => m.Generator(Generators.GuidComb));
		rc.Property(x => x.Name);
		rc.ManyToOne(x => x.Component1, m => { m.Column("Component1Id"); m.NotNullable(true); });
		rc.ManyToOne(x => x.Component2, m => { m.Column("Component2Id"); m.NotNullable(false); });
	});
```

Attempted query:
```cs
	ICriteria tagCriteria = session.CreateCriteria(typeof(Tag), "t");
	tagCriteria.CreateCriteria("Component1", "c1");
	tagCriteria.CreateCriteria("Component2", "c2", JoinType.LeftOuterJoin);

	IProjection projectNameProjection;
	{
		// create correlated subquery
		var projectCriteria = DetachedCriteria.For(typeof(Project), "p");

		// the problem appears when the outer query references are in a Conditional:
		var conditionalCorrelationProjection = Projections.Conditional(
			Restrictions.IsNotNull(Projections.Property("t.Component2")),
			Projections.Property("c2.Project"),
			Projections.Property("c1.Project"));
		projectCriteria.Add(Restrictions.EqProperty("p.Id", conditionalCorrelationProjection));

		projectCriteria.SetProjection(Projections.Property("p.Name"));

		projectNameProjection = Projections.SubQuery(projectCriteria);
	}

	tagCriteria.Add(Restrictions.Eq(projectNameProjection, "Beta"));

	// throws exception
	tagCriteria.List();
````

Exception data:
```
 SubqueryCorrelatedThroughConditional
   Source: FixtureByCode.cs line 41
   Duration: 458 ms

  Message: 
    NHibernate.QueryException : could not resolve property: c2.Project of: NHibernate.Test.NHSpecificTest.GH9999.Project
  Stack Trace: 
    AbstractPropertyMapping.ToType(String propertyName) line 37
    AbstractEntityPersister.ToType(String propertyName) line 2065
    CriteriaQueryTranslator.GetType(ICriteria subcriteria, String propertyName) line 810
    PropertyProjection.GetTypes(ICriteria criteria, ICriteriaQuery criteriaQuery) line 50
    ConditionalProjection.GetTypes(ICriteria criteria, ICriteriaQuery criteriaQuery) line 56
    SimpleProjection.GetColumnCount(ICriteria criteria, ICriteriaQuery criteriaQuery) line 79
    SimpleProjection.GetColumnAliases(Int32 position, ICriteria criteria, ICriteriaQuery criteriaQuery) line 41
    ConditionalProjection.ToSqlString(ICriteria criteria, Int32 position, ICriteriaQuery criteriaQuery) line 50
    CriterionUtil.GetProjectionColumns(IProjection projection, ICriteriaQuery criteriaQuery, ICriteria criteria) line 98
    CriterionUtil.GetColumnNamesAsSqlStringParts(IProjection projection, ICriteriaQuery criteriaQuery, ICriteria criteria) line 71
    CriterionUtil.GetColumnNamesAsSqlStringParts(String propertyName, IProjection projection, ICriteriaQuery criteriaQuery, ICriteria criteria) line 61
    PropertyExpression.ToSqlString(ICriteria criteria, ICriteriaQuery criteriaQuery) line 75
    CriteriaQueryTranslator.GetWhereCondition() line 281
    CriteriaJoinWalker.ctor(IOuterJoinLoadable persister, CriteriaQueryTranslator translator, ISessionFactoryImplementor factory, ICriteria criteria, String rootEntityName, IDictionary`2 enabledFilters) line 48
    SubqueryExpression.ToSqlString(ICriteria criteria, ICriteriaQuery criteriaQuery) line 65
    SubqueryProjection.ToSqlString(ICriteria criteria, Int32 loc, ICriteriaQuery criteriaQuery) line 44
    CriterionUtil.GetProjectionColumns(IProjection projection, ICriteriaQuery criteriaQuery, ICriteria criteria) line 98
    CriterionUtil.GetColumnNamesUsingProjection(IProjection projection, ICriteriaQuery criteriaQuery, ICriteria criteria) line 53
    CriterionUtil.GetColumnNamesForSimpleExpression(String propertyName, IProjection projection, ICriteriaQuery criteriaQuery, ICriteria criteria, ICriterion criterion, Object value) line 42
    SimpleExpression.ToSqlString(ICriteria criteria, ICriteriaQuery criteriaQuery) line 81
    CriteriaQueryTranslator.GetWhereCondition() line 281
    CriteriaJoinWalker.ctor(IOuterJoinLoadable persister, CriteriaQueryTranslator translator, ISessionFactoryImplementor factory, ICriteria criteria, String rootEntityName, IDictionary`2 enabledFilters) line 48
    CriteriaLoader.ctor(IOuterJoinLoadable persister, ISessionFactoryImplementor factory, CriteriaImpl rootCriteria, String rootEntityName, IDictionary`2 enabledFilters) line 69
    SessionImpl.List[T](CriteriaImpl criteria) line 1711
    CriteriaImpl.List[T]() line 296
    CriteriaImpl.List() line 283
    ByCodeFixture.SubqueryCorrelatedThroughConditional() line 100
```

I will post a pull request with a potential fix later.

### PR DESCRIPTION
**Pull request by delta-emil**
This should fix #2454.

The AsyncGenerator was failing for me (I'll open another issue about that) from the build menu, so I wrote the async version of the test by hand.

### CODE REVIEW

**Comment by fredericDelaporte** [comment]
About async generation, you may have maca88/AsyncGenerator#150 issue, see its discussion for a workaround.

**Comment by delta-emil** [comment]
Thank you, @fredericDelaporte, that did allow the AsyncGenerator to run, and it did make a few additional things Async that I'd missed. You should really get that committed.

I also made the test exclude MsSqlCe by SupportsScalarSubSelects of the dialect.

Can you tell me if I need to fix the CodeFactor check's SA1402 violation? It seems like all test cases use the pattern of putting all entity classes in one file.

**Comment by bahusoid** [comment]
Note for future. Looking at stack trace:
```C#
AbstractEntityPersister.ToType(String propertyName) line 2065
CriteriaQueryTranslator.GetType(ICriteria subcriteria, String propertyName) line 810
PropertyProjection.GetTypes(ICriteria criteria, ICriteriaQuery criteriaQuery) line 50
ConditionalProjection.GetTypes(ICriteria criteria, ICriteriaQuery criteriaQuery) line 56
SimpleProjection.GetColumnCount(ICriteria criteria, ICriteriaQuery criteriaQuery) line 79
SimpleProjection.GetColumnAliases(Int32 position, ICriteria criteria, ICriteriaQuery criteriaQuery) line 41
ConditionalProjection.ToSqlString(ICriteria criteria, Int32 position, ICriteriaQuery criteriaQuery) line 50
```

All those calls to generate single alias  `"y" + position + "_"`  seems excessive.

**Comment by delta-emil** [comment]
> 
> 
> Note for future. Looking at stack trace:
> 
> ```cs
> AbstractEntityPersister.ToType(String propertyName) line 2065
> CriteriaQueryTranslator.GetType(ICriteria subcriteria, String propertyName) line 810
> PropertyProjection.GetTypes(ICriteria criteria, ICriteriaQuery criteriaQuery) line 50
> ConditionalProjection.GetTypes(ICriteria criteria, ICriteriaQuery criteriaQuery) line 56
> SimpleProjection.GetColumnCount(ICriteria criteria, ICriteriaQuery criteriaQuery) line 79
> SimpleProjection.GetColumnAliases(Int32 position, ICriteria criteria, ICriteriaQuery criteriaQuery) line 41
> ConditionalProjection.ToSqlString(ICriteria criteria, Int32 position, ICriteriaQuery criteriaQuery) line 50
> ```
> 
> All those calls to generate single alias `"y" + position + "_"` seems excessive.

It was much simpler before it was changed in 1775cc2, which references https://nhibernate.jira.com/browse/NH-3644. The same change also caused #1180. The change seems to be in the direction of supporting multiple aliases for composite columns, but then the code still just only takes the first element of the returned array. Maybe we can move back to the much simpler call`GetColumnAliases(position)` in `ConditionalProjection`'s `ToSqlString`?

**Comment by bahusoid** [comment]
>The change seems to be in the direction of supporting multiple aliases for composite columns, but then the code still just only takes the first element of the returned array. Maybe we can move back to the much simpler callGetColumnAliases(position) in ConditionalProjection's ToSqlString

Yeah I got where those changes come from. Only I think all places should be changed back where replacement was done to analogue of `SimpleProjection.GetColumnAliases(position, criteria, criteriaQuery)[0]' back to `SimpleProjection.GetColumnAliases(position)[0]`

**Comment by delta-emil** [comment]
But discussion of future plans aside, I still think the change submitted here is a correct thing. So how I move it forward?

* Do I need to fix the CodeFactor SA1402 violation in the test code (despite that breaking the pattern set by the other tests)?
* Shall I update the branch to the current master?
* Or should I just leave it alone for the moment, until someone has the chance to review the change?

**Comment by bahusoid** [comment]
> I still think the change submitted here is a correct thing.

Yes. I agree. I didn't do it in first place (when `TryGetType` was introduced to fix similar issue #1312) as I was lazy to compose test case when it's needed and didn't want to change behavior without test case. And I suspect that `GetColumn` method would need to be changed in similar way too.

> Do I need to fix the CodeFactor SA1402

It's fine as is by me. But I guess better to fix it just to make everyone happy.

> Shall I update the branch to the current master?

You can force push it if you want to make it look clean. But don't sweat on it (as long GitHub's Update Branch works without conflicts)

**Review by bahusoid — DISMISSED** [review]

**Review by hazzik — APPROVED** [review]

**Review by hazzik — APPROVED** [review]

**Review by bahusoid — APPROVED** [review]

**Pull request merged**
