### PR TITLE
NH-3470 - Allow Session.Query to load entities as read-only

### PR DESCRIPTION
**Pull request by rjperes**
https://nhibernate.jira.com/browse/NH-3470

### CODE REVIEW

**Comment by hazzik** [comment]
Why?

**Comment by hazzik** [comment]
@rjperes why? There are 3 PR with the same functionality.

**Comment by fredericDelaporte** [comment]
If #601 get merged, this change could be done on top of it with less code and without a new extension method/result operator/....

**Comment by hazzik** [comment]
Replaced by #1500

**Comment by hazzik** [comment]
Duplicate of #301

**Pull request closed without merging**
